// src/app/[locale]/(with-tabbar)/games/trend/page.tsx
"use client";

import React, { useState, useEffect, useRef } from "react";
import { RefreshCw } from "lucide-react";
import { useRequireLogin } from "@/hooks/useRequireLogin";
import { toast } from "sonner";
import { parseErrorMessage, parseAxiosError, cn } from "@/lib/utils";
import { useFormatter } from "use-intl";

import { lotteryRecord } from "@/api/game";
import { useGameContext } from "../_context";
import {
  LotteryResultItem,
} from "@/types/game.type";

// 走势标签类型
type TrendTab = "nums" | "bigSmall" | "shape" | "mod";

export default function TrendPage() {
  useRequireLogin();
  const format = useFormatter();

  // 从 Context 获取共享的游戏状态
  const {
    activeGame,
    selectedGroupId,
  } = useGameContext();

  // 走势内容标签
  const [trendTab, setTrendTab] = useState<TrendTab>("nums");
  const [trendList, setTrendList] = useState<LotteryResultItem[]>([]);
  const [isLoadingTrend, setIsLoadingTrend] = useState(false);

  // 期数选择
  const [periodCount, setPeriodCount] = useState(30);
  const periodOptions = [30, 50, 100];

  // 当游戏或分组变化时获取走势数据
  const prevGameIdRef = useRef<number | null>(null);
  const prevGroupIdRef = useRef<number | null>(null);

  useEffect(() => {
    if (!activeGame || !selectedGroupId) return;

    // 检查是否是相同的游戏和分组，避免重复请求
    if (prevGameIdRef.current === activeGame.id && prevGroupIdRef.current === selectedGroupId) {
      return;
    }

    prevGameIdRef.current = activeGame.id;
    prevGroupIdRef.current = selectedGroupId;

    // 获取走势数据
    fetchTrendData(activeGame.id, selectedGroupId, periodCount);
  }, [activeGame, selectedGroupId]);

  const fetchTrendData = async (lotteryId: number, groupId: number, count: number) => {
    try {
      setIsLoadingTrend(true);
      const res = await lotteryRecord({
        lottery_id: lotteryId,
        game_group_id: groupId,
        page: 1,
        pageSize: count,
      });

      if (res.code === 200 && res.data) {
        setTrendList(res.data.list || []);
      } else {
        toast.error(parseErrorMessage(res, "获取走势数据失败"));
        setTrendList([]);
      }
    } catch (error) {
      toast.error(parseAxiosError(error, "获取走势数据失败，请稍后重试"));
      setTrendList([]);
    } finally {
      setIsLoadingTrend(false);
    }
  };

  const handlePeriodChange = (count: number) => {
    setPeriodCount(count);
    if (activeGame) {
      fetchTrendData(activeGame.id, selectedGroupId, count);
    }
  };

  const handleRefresh = () => {
    if (activeGame) {
      fetchTrendData(activeGame.id, selectedGroupId, periodCount);
    }
  };

  // 获取期号
  const getExpectNo = (item: LotteryResultItem): string => {
    const expectNo = item.final_res?.expectNo || item.final_res?.expect_no || item.expect_no;
    if (!expectNo) return "--";
    return String(expectNo).slice(-7);
  };

  // 获取开奖号码数组
  const getNums = (item: LotteryResultItem): string[] => {
    const nums = item.final_res?.nums || item.action_no_num;
    if (!nums) return [];
    if (Array.isArray(nums)) return nums;
    if (typeof nums === "object") return Object.values(nums);
    return String(nums).split(",");
  };

  // 获取和值
  const getSum = (item: LotteryResultItem): number | string => {
    return item.final_res?.sum ?? "--";
  };

  // 获取形态
  const getShape = (item: LotteryResultItem): string => {
    const shape = item.final_res?.shape || "--";
    if (shape === 'bao') return "豹子";
    if (shape === 'shun') return "顺子";
    if (shape === 'ban') return "半顺";
    if (shape === 'dui') return "对子";
    if (shape === 'za') return "杂六";
    return "--";
  };

  // 获取龙虎豹
  const getLungFuPao = (item: LotteryResultItem): string => {
    const lungFuPao = item.final_res?.lungFuPao || "--";
    if (lungFuPao === 'Dragon' || lungFuPao === 'dragon') return "龙";
    if (lungFuPao === 'Tiger' || lungFuPao === 'tiger') return "虎";
    if (lungFuPao === 'Leopard' || lungFuPao === 'leopard') return "豹";
    return "--";
  };

  // 走势标签配置
  const trendTabs = [
    { key: "nums" as TrendTab, label: "号码" },
    { key: "bigSmall" as TrendTab, label: "大小单双" },
    { key: "mod" as TrendTab, label: "取模" },
    { key: "shape" as TrendTab, label: "形态" },
  ];

  return (
    <div className="bg-gray-100 dark:bg-black">
      {/* 走势表 */}
      <div className="bg-white m-3 rounded-lg shadow overflow-hidden">
        {/* 顶部控制栏 */}
        <div className="flex justify-between items-center px-3 py-2 border-b bg-gray-50">
          <div className="flex items-center gap-2">
            <span className="text-sm text-gray-600">显示</span>
            <select
              value={periodCount}
              onChange={(e) => handlePeriodChange(Number(e.target.value))}
              className="px-2 py-1 text-sm border border-gray-300 rounded bg-white"
            >
              {periodOptions.map((opt) => (
                <option key={opt} value={opt}>{opt}期</option>
              ))}
            </select>
          </div>
          <button
            onClick={handleRefresh}
            disabled={isLoadingTrend}
            className="flex items-center gap-1 text-sm text-gray-600 hover:text-red-600 disabled:opacity-50"
          >
            <RefreshCw size={14} className={isLoadingTrend ? "animate-spin" : ""} />
            刷新
          </button>
        </div>

        {/* 走势标签切换 */}
        <div className="flex border-b bg-white">
          {trendTabs.map((t) => (
            <button
              key={t.key}
              onClick={() => setTrendTab(t.key)}
              className={cn(
                "flex-1 py-2.5 text-xs font-medium transition-colors",
                trendTab === t.key
                  ? "text-red-600 bg-red-50 border-b-2 border-red-600"
                  : "text-gray-600 hover:bg-gray-50"
              )}
            >
              {t.label}
            </button>
          ))}
        </div>

        {/* 表头 */}
        <div className="flex text-xs bg-gray-100 border-b font-medium">
          <div className="w-16 py-2 text-center border-r flex-shrink-0">期号</div>

          {/* 号码表头 */}
          {trendTab === "nums" && (
            <div className="flex-1 flex">
              <div className="flex-1 py-2 text-center border-r text-gray-600">开奖号码</div>
              <div className="w-12 py-2 text-center text-gray-600">和值</div>
            </div>
          )}

          {/* 大小单双表头 - 6列 */}
          {trendTab === "bigSmall" && (
            <div className="flex-1 flex text-center">
              <div className="flex-1 py-2 border-r text-red-600">大</div>
              <div className="flex-1 py-2 border-r text-green-600">小</div>
              <div className="flex-1 py-2 border-r text-orange-600">单</div>
              <div className="flex-1 py-2 border-r text-blue-600">双</div>
              <div className="flex-1 py-2 border-r text-purple-600">中</div>
              <div className="flex-1 py-2 text-cyan-600">边</div>
            </div>
          )}

          {/* 形态表头 */}
          {trendTab === "shape" && (
            <div className="flex-1 flex text-center">
              <div className="flex-1 py-2 border-r text-pink-600">豹子</div>
              <div className="flex-1 py-2 border-r text-red-600">顺子</div>
              <div className="flex-1 py-2 border-r text-orange-600">半顺</div>
              <div className="flex-1 py-2 border-r text-blue-600">对子</div>
              <div className="flex-1 py-2 border-r text-gray-600">杂六</div>
              <div className="w-px bg-gray-300"></div>
              <div className="flex-1 py-2 border-r text-red-600">龙</div>
              <div className="flex-1 py-2 border-r text-blue-600">虎</div>
              <div className="flex-1 py-2 text-purple-600">豹</div>
            </div>
          )}

          {/* 取模表头 - 双层 */}
          {trendTab === "mod" && (
            <div className="flex-1 flex flex-col">
              {/* 第一层：模3/模4/模5 */}
              <div className="flex border-b">
                <div className="flex-[3] py-1 text-center border-r bg-gray-200 font-bold">模3</div>
                <div className="flex-[4] py-1 text-center border-r bg-amber-100 font-bold">模4</div>
                <div className="flex-[5] py-1 text-center bg-teal-100 font-bold">模5</div>
              </div>
              {/* 第二层：具体数值 */}
              <div className="flex">
                {/* 模3: 0,1,2 */}
                {[0, 1, 2].map((n) => (
                  <div key={`m3-${n}`} className="flex-1 py-1 text-center border-r text-gray-600">{n}</div>
                ))}
                {/* 模4: 0,1,2,3 */}
                {[0, 1, 2, 3].map((n) => (
                  <div key={`m4-${n}`} className="flex-1 py-1 text-center border-r text-gray-600">{n}</div>
                ))}
                {/* 模5: 0,1,2,3,4 */}
                {[0, 1, 2, 3, 4].map((n, i) => (
                  <div key={`m5-${n}`} className={cn("flex-1 py-1 text-center text-gray-600", i < 4 && "border-r")}>{n}</div>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* 数据列表 */}
        {isLoadingTrend ? (
          <div className="flex justify-center items-center py-8">
            <div className="inline-block h-6 w-6 animate-spin rounded-full border-4 border-solid border-red-600 border-r-transparent"></div>
            <span className="ml-2 text-gray-600">加载走势数据中...</span>
          </div>
        ) : trendList.length === 0 ? (
          <div className="text-center py-8 text-gray-500">
            暂无走势数据
          </div>
        ) : (
          <div className="max-h-[60vh] overflow-y-auto">
            {trendList
              .filter((item) => {
                // 过滤掉没有开奖号码的记录
                const nums = getNums(item);
                return nums.length > 0 && nums.some(n => n && n !== "");
              })
              .map((item, index) => {
              const fr = item.final_res;
              const nums = getNums(item);
              const shape = fr?.shape;
              const lungFuPao = fr?.lungFuPao;
              const mod3 = fr?.mod3;
              const mod4 = fr?.mod4;
              const mod5 = fr?.mod5;

              return (
                <div
                  key={`${item.id || index}`}
                  className="flex text-xs border-b hover:bg-gray-50"
                >
                  {/* 期号列 - 固定 */}
                  <div className="w-16 py-2.5 text-center border-r flex-shrink-0 text-gray-700 font-medium bg-gray-50">
                    {getExpectNo(item)}
                  </div>

                  {/* 号码 - 开奖号码 + 和值 */}
                  {trendTab === "nums" && (
                    <div className="flex-1 flex">
                      <div className="flex-1 py-2 flex items-center justify-center gap-3 border-r">
                        {nums.map((num, i) => (
                          <span
                            key={i}
                            className="inline-flex h-7 w-7 items-center justify-center rounded-full bg-gradient-to-b from-gray-500 to-gray-700 text-white text-sm font-bold shadow"
                          >
                            {num}
                          </span>
                        ))}
                      </div>
                      <div className="w-12 py-2 flex items-center justify-center">
                        <span className="inline-flex h-7 min-w-7 px-1.5 items-center justify-center rounded-full bg-gradient-to-b from-red-500 to-red-600 text-white text-sm font-bold shadow">
                          {getSum(item)}
                        </span>
                      </div>
                    </div>
                  )}

                  {/* 大小单双 - 6列，命中高亮 */}
                  {trendTab === "bigSmall" && (
                    <div className="flex-1 flex text-center">
                      {/* 大 */}
                      <div className={cn(
                        "flex-1 py-2.5 border-r flex items-center justify-center",
                        fr?.bigSmall === "大" && "bg-red-100"
                      )}>
                        {fr?.bigSmall === "大" && (
                          <span className="inline-flex h-6 w-6 items-center justify-center rounded-full bg-red-500 text-white text-xs font-bold">大</span>
                        )}
                      </div>
                      {/* 小 */}
                      <div className={cn(
                        "flex-1 py-2.5 border-r flex items-center justify-center",
                        fr?.bigSmall === "小" && "bg-green-100"
                      )}>
                        {fr?.bigSmall === "小" && (
                          <span className="inline-flex h-6 w-6 items-center justify-center rounded-full bg-green-500 text-white text-xs font-bold">小</span>
                        )}
                      </div>
                      {/* 单 */}
                      <div className={cn(
                        "flex-1 py-2.5 border-r flex items-center justify-center",
                        fr?.oddEven === "单" && "bg-orange-100"
                      )}>
                        {fr?.oddEven === "单" && (
                          <span className="inline-flex h-6 w-6 items-center justify-center rounded-full bg-orange-500 text-white text-xs font-bold">单</span>
                        )}
                      </div>
                      {/* 双 */}
                      <div className={cn(
                        "flex-1 py-2.5 border-r flex items-center justify-center",
                        fr?.oddEven === "双" && "bg-blue-100"
                      )}>
                        {fr?.oddEven === "双" && (
                          <span className="inline-flex h-6 w-6 items-center justify-center rounded-full bg-blue-500 text-white text-xs font-bold">双</span>
                        )}
                      </div>
                      {/* 中 */}
                      <div className={cn(
                        "flex-1 py-2.5 border-r flex items-center justify-center",
                        fr?.middleSide === "中" && "bg-purple-100"
                      )}>
                        {fr?.middleSide === "中" && (
                          <span className="inline-flex h-6 w-6 items-center justify-center rounded-full bg-purple-500 text-white text-xs font-bold">中</span>
                        )}
                      </div>
                      {/* 边 */}
                      <div className={cn(
                        "flex-1 py-2.5 flex items-center justify-center",
                        fr?.middleSide === "边" && "bg-cyan-100"
                      )}>
                        {fr?.middleSide === "边" && (
                          <span className="inline-flex h-6 w-6 items-center justify-center rounded-full bg-cyan-500 text-white text-xs font-bold">边</span>
                        )}
                      </div>
                    </div>
                  )}

                  {/* 形态 - 8列，命中高亮 */}
                  {trendTab === "shape" && (
                    <div className="flex-1 flex text-center">
                      {/* 豹子 */}
                      <div className={cn(
                        "flex-1 py-2.5 border-r flex items-center justify-center",
                        shape === "bao" && "bg-pink-100"
                      )}>
                        {shape === "bao" && (
                          <span className="inline-flex h-5 w-5 items-center justify-center rounded-full bg-pink-500 text-white text-[10px] font-bold">豹</span>
                        )}
                      </div>
                      {/* 顺子 */}
                      <div className={cn(
                        "flex-1 py-2.5 border-r flex items-center justify-center",
                        shape === "shun" && "bg-red-100"
                      )}>
                        {shape === "shun" && (
                          <span className="inline-flex h-5 w-5 items-center justify-center rounded-full bg-red-500 text-white text-[10px] font-bold">顺</span>
                        )}
                      </div>
                      {/* 半顺 */}
                      <div className={cn(
                        "flex-1 py-2.5 border-r flex items-center justify-center",
                        shape === "ban" && "bg-orange-100"
                      )}>
                        {shape === "ban" && (
                          <span className="inline-flex h-5 w-5 items-center justify-center rounded-full bg-orange-500 text-white text-[10px] font-bold">半</span>
                        )}
                      </div>
                      {/* 对子 */}
                      <div className={cn(
                        "flex-1 py-2.5 border-r flex items-center justify-center",
                        shape === "dui" && "bg-blue-100"
                      )}>
                        {shape === "dui" && (
                          <span className="inline-flex h-5 w-5 items-center justify-center rounded-full bg-blue-500 text-white text-[10px] font-bold">对</span>
                        )}
                      </div>
                      {/* 杂六 */}
                      <div className={cn(
                        "flex-1 py-2.5 border-r flex items-center justify-center",
                        shape === "za" && "bg-gray-200"
                      )}>
                        {shape === "za" && (
                          <span className="inline-flex h-5 w-5 items-center justify-center rounded-full bg-gray-500 text-white text-[10px] font-bold">杂</span>
                        )}
                      </div>
                      {/* 分隔线 */}
                      <div className="w-px bg-gray-300"></div>
                      {/* 龙 */}
                      <div className={cn(
                        "flex-1 py-2.5 border-r flex items-center justify-center",
                        (lungFuPao === "Dragon" || lungFuPao === "dragon") && "bg-red-100"
                      )}>
                        {(lungFuPao === "Dragon" || lungFuPao === "dragon") && (
                          <span className="inline-flex h-5 w-5 items-center justify-center rounded-full bg-red-500 text-white text-[10px] font-bold">龙</span>
                        )}
                      </div>
                      {/* 虎 */}
                      <div className={cn(
                        "flex-1 py-2.5 border-r flex items-center justify-center",
                        (lungFuPao === "Tiger" || lungFuPao === "tiger") && "bg-blue-100"
                      )}>
                        {(lungFuPao === "Tiger" || lungFuPao === "tiger") && (
                          <span className="inline-flex h-5 w-5 items-center justify-center rounded-full bg-blue-500 text-white text-[10px] font-bold">虎</span>
                        )}
                      </div>
                      {/* 豹 */}
                      <div className={cn(
                        "flex-1 py-2.5 flex items-center justify-center",
                        (lungFuPao === "Leopard" || lungFuPao === "leopard") && "bg-purple-100"
                      )}>
                        {(lungFuPao === "Leopard" || lungFuPao === "leopard") && (
                          <span className="inline-flex h-5 w-5 items-center justify-center rounded-full bg-purple-500 text-white text-[10px] font-bold">豹</span>
                        )}
                      </div>
                    </div>
                  )}

                  {/* 取模 - 12列 (3+4+5)，命中高亮 */}
                  {trendTab === "mod" && (
                    <div className="flex-1 flex text-center">
                      {/* 模3: 0,1,2 */}
                      {[0, 1, 2].map((n) => (
                        <div
                          key={`m3-${n}`}
                          className={cn(
                            "flex-1 py-2.5 border-r flex items-center justify-center",
                            mod3 === n && "bg-gray-200"
                          )}
                        >
                          {mod3 === n && (
                            <span className="inline-flex h-5 w-5 items-center justify-center rounded-full bg-gray-600 text-white text-xs font-bold">{n}</span>
                          )}
                        </div>
                      ))}
                      {/* 模4: 0,1,2,3 */}
                      {[0, 1, 2, 3].map((n) => (
                        <div
                          key={`m4-${n}`}
                          className={cn(
                            "flex-1 py-2.5 border-r flex items-center justify-center",
                            mod4 === n && "bg-amber-100"
                          )}
                        >
                          {mod4 === n && (
                            <span className="inline-flex h-5 w-5 items-center justify-center rounded-full bg-amber-500 text-white text-xs font-bold">{n}</span>
                          )}
                        </div>
                      ))}
                      {/* 模5: 0,1,2,3,4 */}
                      {[0, 1, 2, 3, 4].map((n, i) => (
                        <div
                          key={`m5-${n}`}
                          className={cn(
                            "flex-1 py-2.5 flex items-center justify-center",
                            i < 4 && "border-r",
                            mod5 === n && "bg-teal-100"
                          )}
                        >
                          {mod5 === n && (
                            <span className="inline-flex h-5 w-5 items-center justify-center rounded-full bg-teal-500 text-white text-xs font-bold">{n}</span>
                          )}
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        )}
      </div>

    </div>
  );
}

// src/views/games/trend.vue
<script setup lang="ts">
import { ref, watch, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import { RefreshCw } from 'lucide-vue-next'
import { lotteryRecord } from '@/api/game'
import { toast } from '@/composables/useToast'
import { cn } from '@/utils'
import type { LotteryResultItem } from '@/types/game.type'

type TrendTab = 'nums' | 'bigSmall' | 'shape' | 'mod'

const route = useRoute()

const trendTab = ref<TrendTab>('nums')
const trendList = ref<LotteryResultItem[]>([])
const isLoadingTrend = ref(false)
const periodCount = ref(30)
const periodOptions = [30, 50, 100]

// 从路由获取参数
const getLotteryId = () => Number(route.query.lottery_id) || 0
const getGroupId = () => Number(route.query.group_id) || 0

// 获取走势数据
const fetchTrendData = async (count: number = 30) => {
  const lotteryId = getLotteryId()
  const groupId = getGroupId()

  if (!lotteryId) return

  try {
    isLoadingTrend.value = true
    const res = await lotteryRecord({
      lottery_id: lotteryId,
      game_group_id: groupId,
      page: 1,
      pageSize: count
    })

    if (res.code === 200 && res.data) {
      trendList.value = res.data.list || []
    } else {
      toast.error(res.message || '获取走势数据失败')
      trendList.value = []
    }
  } catch (error) {
    toast.error('获取走势数据失败，请稍后重试')
    trendList.value = []
  } finally {
    isLoadingTrend.value = false
  }
}

const handlePeriodChange = (count: number) => {
  periodCount.value = count
  fetchTrendData(count)
}

const handleRefresh = () => {
  fetchTrendData(periodCount.value)
}

const getExpectNo = (item: LotteryResultItem): string => {
  const expectNo = item.final_res?.expectNo || item.final_res?.expect_no || item.expect_no
  if (!expectNo) return '--'
  return String(expectNo).slice(-7)
}

const getNums = (item: LotteryResultItem): string[] => {
  const nums = item.final_res?.nums || item.action_no_num
  if (!nums) return []
  if (Array.isArray(nums)) return nums
  if (typeof nums === 'object') return Object.values(nums)
  return String(nums).split(',')
}

const getSum = (item: LotteryResultItem): number | string => {
  return item.final_res?.sum ?? '--'
}

const trendTabs = [
  { key: 'nums' as TrendTab, label: '号码' },
  { key: 'bigSmall' as TrendTab, label: '大小单双' },
  { key: 'mod' as TrendTab, label: '取模' },
  { key: 'shape' as TrendTab, label: '形态' }
]

const filteredTrendList = () => {
  return trendList.value.filter((item) => {
    const nums = getNums(item)
    return nums.length > 0 && nums.some(n => n && n !== '')
  })
}

// 监听路由参数变化，重新加载数据
watch(
  () => [route.query.lottery_id, route.query.group_id],
  () => {
    fetchTrendData(periodCount.value)
  }
)

// 组件挂载时加载数据
onMounted(() => {
  fetchTrendData(periodCount.value)
})
</script>

<template>
  <div class="bg-gray-100">
    <!-- 走势表 -->
    <div class="bg-white m-3 rounded-lg shadow overflow-hidden">
      <!-- 顶部控制栏 -->
      <div class="flex justify-between items-center px-3 py-2 border-b bg-gray-50">
        <div class="flex items-center gap-2">
          <span class="text-sm text-gray-600">显示</span>
          <select
            v-model="periodCount"
            @change="handlePeriodChange(periodCount)"
            class="px-2 py-1 text-sm border border-gray-300 rounded bg-white"
          >
            <option v-for="opt in periodOptions" :key="opt" :value="opt">{{ opt }}期</option>
          </select>
        </div>
        <button
          @click="handleRefresh"
          :disabled="isLoadingTrend"
          class="flex items-center gap-1 text-sm text-gray-600 hover:text-red-600 disabled:opacity-50"
        >
          <RefreshCw :size="14" :class="isLoadingTrend ? 'animate-spin' : ''" />
          刷新
        </button>
      </div>

      <!-- 走势标签切换 -->
      <div class="flex border-b bg-white">
        <button
          v-for="t in trendTabs"
          :key="t.key"
          @click="trendTab = t.key"
          :class="cn(
            'flex-1 py-2.5 text-xs font-medium transition-colors',
            trendTab === t.key
              ? 'text-red-600 bg-red-50 border-b-2 border-red-600'
              : 'text-gray-600 hover:bg-gray-50'
          )"
        >
          {{ t.label }}
        </button>
      </div>

      <!-- 表头 -->
      <div class="flex text-xs bg-gray-100 border-b font-medium">
        <div class="w-16 py-2 text-center border-r flex-shrink-0">期号</div>

        <!-- 号码表头 -->
        <template v-if="trendTab === 'nums'">
          <div class="flex-1 flex">
            <div class="flex-1 py-2 text-center border-r text-gray-600">开奖号码</div>
            <div class="w-12 py-2 text-center text-gray-600">和值</div>
          </div>
        </template>

        <!-- 大小单双表头 -->
        <template v-if="trendTab === 'bigSmall'">
          <div class="flex-1 flex text-center">
            <div class="flex-1 py-2 border-r text-red-600">大</div>
            <div class="flex-1 py-2 border-r text-green-600">小</div>
            <div class="flex-1 py-2 border-r text-orange-600">单</div>
            <div class="flex-1 py-2 border-r text-blue-600">双</div>
            <div class="flex-1 py-2 border-r text-purple-600">中</div>
            <div class="flex-1 py-2 text-cyan-600">边</div>
          </div>
        </template>

        <!-- 形态表头 -->
        <template v-if="trendTab === 'shape'">
          <div class="flex-1 flex text-center">
            <div class="flex-1 py-2 border-r text-pink-600">豹子</div>
            <div class="flex-1 py-2 border-r text-red-600">顺子</div>
            <div class="flex-1 py-2 border-r text-orange-600">半顺</div>
            <div class="flex-1 py-2 border-r text-blue-600">对子</div>
            <div class="flex-1 py-2 border-r text-gray-600">杂六</div>
            <div class="w-px bg-gray-300"></div>
            <div class="flex-1 py-2 border-r text-red-600">龙</div>
            <div class="flex-1 py-2 border-r text-blue-600">虎</div>
            <div class="flex-1 py-2 text-purple-600">豹</div>
          </div>
        </template>

        <!-- 取模表头 -->
        <template v-if="trendTab === 'mod'">
          <div class="flex-1 flex flex-col">
            <div class="flex border-b">
              <div class="flex-[3] py-1 text-center border-r bg-gray-200 font-bold">模3</div>
              <div class="flex-[4] py-1 text-center border-r bg-amber-100 font-bold">模4</div>
              <div class="flex-[5] py-1 text-center bg-teal-100 font-bold">模5</div>
            </div>
            <div class="flex">
              <div v-for="n in [0, 1, 2]" :key="`m3-${n}`" class="flex-1 py-1 text-center border-r text-gray-600">{{ n }}</div>
              <div v-for="n in [0, 1, 2, 3]" :key="`m4-${n}`" class="flex-1 py-1 text-center border-r text-gray-600">{{ n }}</div>
              <div v-for="(n, i) in [0, 1, 2, 3, 4]" :key="`m5-${n}`" :class="cn('flex-1 py-1 text-center text-gray-600', i < 4 && 'border-r')">{{ n }}</div>
            </div>
          </div>
        </template>
      </div>

      <!-- 数据列表 -->
      <div v-if="isLoadingTrend" class="flex justify-center items-center py-8">
        <div class="inline-block h-6 w-6 animate-spin rounded-full border-4 border-solid border-red-600 border-r-transparent"></div>
        <span class="ml-2 text-gray-600">加载走势数据中...</span>
      </div>

      <div v-else-if="trendList.length === 0" class="text-center py-8 text-gray-500">
        暂无走势数据
      </div>

      <div v-else class="max-h-[60vh] overflow-y-auto">
        <div
          v-for="(item, index) in filteredTrendList()"
          :key="`${item.id || index}`"
          class="flex text-xs border-b hover:bg-gray-50"
        >
          <!-- 期号列 -->
          <div class="w-16 py-2.5 text-center border-r flex-shrink-0 text-gray-700 font-medium bg-gray-50">
            {{ getExpectNo(item) }}
          </div>

          <!-- 号码 -->
          <template v-if="trendTab === 'nums'">
            <div class="flex-1 flex">
              <div class="flex-1 py-2 flex items-center justify-center gap-3 border-r">
                <span
                  v-for="(num, i) in getNums(item)"
                  :key="i"
                  class="inline-flex h-7 w-7 items-center justify-center rounded-full bg-gradient-to-b from-gray-500 to-gray-700 text-white text-sm font-bold shadow"
                >
                  {{ num }}
                </span>
              </div>
              <div class="w-12 py-2 flex items-center justify-center">
                <span class="inline-flex h-7 min-w-7 px-1.5 items-center justify-center rounded-full bg-gradient-to-b from-red-500 to-red-600 text-white text-sm font-bold shadow">
                  {{ getSum(item) }}
                </span>
              </div>
            </div>
          </template>

          <!-- 大小单双 -->
          <template v-if="trendTab === 'bigSmall'">
            <div class="flex-1 flex text-center">
              <div :class="cn('flex-1 py-2.5 border-r flex items-center justify-center', item.final_res?.bigSmall === '大' && 'bg-red-100')">
                <span v-if="item.final_res?.bigSmall === '大'" class="inline-flex h-6 w-6 items-center justify-center rounded-full bg-red-500 text-white text-xs font-bold">大</span>
              </div>
              <div :class="cn('flex-1 py-2.5 border-r flex items-center justify-center', item.final_res?.bigSmall === '小' && 'bg-green-100')">
                <span v-if="item.final_res?.bigSmall === '小'" class="inline-flex h-6 w-6 items-center justify-center rounded-full bg-green-500 text-white text-xs font-bold">小</span>
              </div>
              <div :class="cn('flex-1 py-2.5 border-r flex items-center justify-center', item.final_res?.oddEven === '单' && 'bg-orange-100')">
                <span v-if="item.final_res?.oddEven === '单'" class="inline-flex h-6 w-6 items-center justify-center rounded-full bg-orange-500 text-white text-xs font-bold">单</span>
              </div>
              <div :class="cn('flex-1 py-2.5 border-r flex items-center justify-center', item.final_res?.oddEven === '双' && 'bg-blue-100')">
                <span v-if="item.final_res?.oddEven === '双'" class="inline-flex h-6 w-6 items-center justify-center rounded-full bg-blue-500 text-white text-xs font-bold">双</span>
              </div>
              <div :class="cn('flex-1 py-2.5 border-r flex items-center justify-center', item.final_res?.middleSide === '中' && 'bg-purple-100')">
                <span v-if="item.final_res?.middleSide === '中'" class="inline-flex h-6 w-6 items-center justify-center rounded-full bg-purple-500 text-white text-xs font-bold">中</span>
              </div>
              <div :class="cn('flex-1 py-2.5 flex items-center justify-center', item.final_res?.middleSide === '边' && 'bg-cyan-100')">
                <span v-if="item.final_res?.middleSide === '边'" class="inline-flex h-6 w-6 items-center justify-center rounded-full bg-cyan-500 text-white text-xs font-bold">边</span>
              </div>
            </div>
          </template>

          <!-- 形态 -->
          <template v-if="trendTab === 'shape'">
            <div class="flex-1 flex text-center">
              <div :class="cn('flex-1 py-2.5 border-r flex items-center justify-center', item.final_res?.shape === 'bao' && 'bg-pink-100')">
                <span v-if="item.final_res?.shape === 'bao'" class="inline-flex h-5 w-5 items-center justify-center rounded-full bg-pink-500 text-white text-[10px] font-bold">豹</span>
              </div>
              <div :class="cn('flex-1 py-2.5 border-r flex items-center justify-center', item.final_res?.shape === 'shun' && 'bg-red-100')">
                <span v-if="item.final_res?.shape === 'shun'" class="inline-flex h-5 w-5 items-center justify-center rounded-full bg-red-500 text-white text-[10px] font-bold">顺</span>
              </div>
              <div :class="cn('flex-1 py-2.5 border-r flex items-center justify-center', item.final_res?.shape === 'ban' && 'bg-orange-100')">
                <span v-if="item.final_res?.shape === 'ban'" class="inline-flex h-5 w-5 items-center justify-center rounded-full bg-orange-500 text-white text-[10px] font-bold">半</span>
              </div>
              <div :class="cn('flex-1 py-2.5 border-r flex items-center justify-center', item.final_res?.shape === 'dui' && 'bg-blue-100')">
                <span v-if="item.final_res?.shape === 'dui'" class="inline-flex h-5 w-5 items-center justify-center rounded-full bg-blue-500 text-white text-[10px] font-bold">对</span>
              </div>
              <div :class="cn('flex-1 py-2.5 border-r flex items-center justify-center', item.final_res?.shape === 'za' && 'bg-gray-200')">
                <span v-if="item.final_res?.shape === 'za'" class="inline-flex h-5 w-5 items-center justify-center rounded-full bg-gray-500 text-white text-[10px] font-bold">杂</span>
              </div>
              <div class="w-px bg-gray-300"></div>
              <div :class="cn('flex-1 py-2.5 border-r flex items-center justify-center', ['Dragon', 'dragon'].includes(item.final_res?.lungFuPao || '') && 'bg-red-100')">
                <span v-if="['Dragon', 'dragon'].includes(item.final_res?.lungFuPao || '')" class="inline-flex h-5 w-5 items-center justify-center rounded-full bg-red-500 text-white text-[10px] font-bold">龙</span>
              </div>
              <div :class="cn('flex-1 py-2.5 border-r flex items-center justify-center', ['Tiger', 'tiger'].includes(item.final_res?.lungFuPao || '') && 'bg-blue-100')">
                <span v-if="['Tiger', 'tiger'].includes(item.final_res?.lungFuPao || '')" class="inline-flex h-5 w-5 items-center justify-center rounded-full bg-blue-500 text-white text-[10px] font-bold">虎</span>
              </div>
              <div :class="cn('flex-1 py-2.5 flex items-center justify-center', ['Leopard', 'leopard'].includes(item.final_res?.lungFuPao || '') && 'bg-purple-100')">
                <span v-if="['Leopard', 'leopard'].includes(item.final_res?.lungFuPao || '')" class="inline-flex h-5 w-5 items-center justify-center rounded-full bg-purple-500 text-white text-[10px] font-bold">豹</span>
              </div>
            </div>
          </template>

          <!-- 取模 -->
          <template v-if="trendTab === 'mod'">
            <div class="flex-1 flex text-center">
              <div v-for="n in [0, 1, 2]" :key="`m3-${n}`" :class="cn('flex-1 py-2.5 border-r flex items-center justify-center', item.final_res?.mod3 === n && 'bg-gray-200')">
                <span v-if="item.final_res?.mod3 === n" class="inline-flex h-5 w-5 items-center justify-center rounded-full bg-gray-600 text-white text-xs font-bold">{{ n }}</span>
              </div>
              <div v-for="n in [0, 1, 2, 3]" :key="`m4-${n}`" :class="cn('flex-1 py-2.5 border-r flex items-center justify-center', item.final_res?.mod4 === n && 'bg-amber-100')">
                <span v-if="item.final_res?.mod4 === n" class="inline-flex h-5 w-5 items-center justify-center rounded-full bg-amber-500 text-white text-xs font-bold">{{ n }}</span>
              </div>
              <div v-for="(n, i) in [0, 1, 2, 3, 4]" :key="`m5-${n}`" :class="cn('flex-1 py-2.5 flex items-center justify-center', i < 4 && 'border-r', item.final_res?.mod5 === n && 'bg-teal-100')">
                <span v-if="item.final_res?.mod5 === n" class="inline-flex h-5 w-5 items-center justify-center rounded-full bg-teal-500 text-white text-xs font-bold">{{ n }}</span>
              </div>
            </div>
          </template>
        </div>
      </div>
    </div>
  </div>
</template>
