// src/views/mine/sign/record/index.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import { signRecords } from '@/api/customer'
import { toast } from '@/composables/useToast'
import type { SignRecordField } from '@/types/customer.type'

const list = ref<SignRecordField[]>([])
const page = ref(1)
const hasMore = ref(true)
const loading = ref(false)
const loadMoreRef = ref<HTMLDivElement | null>(null)
let observer: IntersectionObserver | null = null

const fetchData = async (pageNo: number) => {
  loading.value = true
  try {
    const { code, data, message } = await signRecords({
      pagination: {
        page: pageNo,
        size: 20
      }
    })
    await new Promise((r) => setTimeout(r, 500))
    if (code === 200) {
      if (data.length < 20) {
        hasMore.value = false
      }
      if (pageNo === 1) {
        list.value = []
      }
      list.value = [...list.value, ...data]
    } else {
      toast.error(message)
    }
  } catch (error) {
    toast.error('获取数据失败')
  } finally {
    loading.value = false
  }
}

onMounted(async () => {
  await fetchData(1)

  if (loadMoreRef.value && hasMore.value) {
    observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting && !loading.value) {
          const nextPage = page.value + 1
          page.value = nextPage
          fetchData(nextPage)
        }
      },
      { threshold: 1 }
    )
    observer.observe(loadMoreRef.value)
  }
})

onUnmounted(() => {
  if (observer) {
    observer.disconnect()
  }
})
</script>

<template>
  <!-- 表头 -->
  <div class="grid grid-cols-[1fr_1fr_1fr] px-3 py-2 text-xs text-gray-500 border-b bg-white">
    <div class="text-center">日期</div>
    <div class="text-center">获得积分</div>
    <div class="text-center">获得金豆</div>
  </div>

  <div
    v-for="(item, index) in list"
    :key="`all-key-${index}`"
    class="grid grid-cols-[1fr_1fr_1fr] px-3 py-3 border-b text-sm items-center bg-white"
  >
    <div class="text-center">{{ item?.sign_date || '' }}</div>
    <div class="text-center font-medium text-red-500">+{{ item?.reward_points || 0 }}</div>
    <div class="text-center font-medium text-orange-500">+{{ item?.reward_base_coin || 0 }}</div>
  </div>

  <!-- 底部哨兵 -->
  <div v-if="hasMore" ref="loadMoreRef" class="py-4 text-center text-xs text-gray-400">
    {{ loading ? '加载中...' : '上拉加载更多' }}
  </div>

  <div v-if="!hasMore" class="py-4 text-center text-xs text-gray-400">
    没有更多数据了
  </div>
</template>

// src/app/[locale]/(with-tabbar)/mine/spread/record/page.tsx
"use client"

import {useEffect, useRef, useState} from "react";
import * as React from "react";
import {useTranslations} from "use-intl";
import {recommendCustomers} from "@/api/customer";
import {toast} from "sonner";
import {RecommendCustomer} from "@/types/customer.type";

export default function AllPage() {
  const _t = useTranslations();

  const [list, setList] = useState<RecommendCustomer[]>([]);
  const [page, setPage] = useState(1);
  const [hasMore, setHasMore] = useState(true);
  const [loading, setLoading] = useState(false);

  const loadMoreRef = useRef<HTMLDivElement | null>(null);

  const fetchData = async (pageNo: number) => {
    setLoading(true);

    // 模拟接口
    const {code, data, message} = await recommendCustomers({
      pagination: {
        page: pageNo,
        size: 20,
      }
    })
    await new Promise((r) => setTimeout(r, 1000));
    if (code === 200) {
      setLoading(false);
      if (data.length < 20) {
        setHasMore(false); // 模拟 5 页结束
      }
      setList((prev) => [...prev, ...data]);
    } else {
      toast.error(message);
    }
  };

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    fetchData(1).then(() => {});
  }, []);

  useEffect(() => {
    if (!loadMoreRef.current || !hasMore) return;

    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting && !loading) {
          const nextPage = page + 1;
          setPage(nextPage);
          fetchData(nextPage).then(() => {});
        }
      },
      {threshold: 1}
    );

    observer.observe(loadMoreRef.current);

    return () => observer.disconnect();
  }, [page, hasMore, loading]);

  return (
    <>
      {/* 表头 */}
      <div className="grid grid-cols-[0.5fr_1fr_1fr_1fr] px-3 py-2 text-xs text-muted-foreground border-b">
        <div className="text-center">{_t("recommend.record-table-header-1")}</div>
        <div className="text-center">{_t("recommend.record-table-header-2")}</div>
        <div className="text-center">{_t("recommend.record-table-header-3")}</div>
        <div className="text-center">{_t("recommend.record-table-header-4")}</div>
      </div>

      {list.map((item, index) => (
        <div
          key={`record-key-${index}`}
          className="grid grid-cols-[0.5fr_1fr_1fr_1fr] px-3 py-3 border-b text-sm items-center"
        >
          {/* 昵称 */}
          <div className="leading-tight">{item?.nickname || ''}</div>

          {/* 生态值 */}
          <div className="text-center font-medium">{item?.experience || 0}</div>

          {/* 今日提成 */}
          <div className="text-center font-medium">{item?.tzpoints || 0}</div>

          {/* 累计提成 */}
          <div className="text-center font-medium">{item?.tgall || 0}</div>
        </div>
      ))}

      {/* 底部哨兵 */}
      {hasMore && (
        <div ref={loadMoreRef} className="py-4 text-center text-xs text-gray-400">
          {loading ? _t("common.loading") : _t("common.loading-hit")}
        </div>
      )}

      {!hasMore && (
        <div className="py-4 text-center text-xs text-gray-400">
          {_t("common.loading-list-empty")}
        </div>
      )}
    </>
  )
}
