// src/app/[locale]/(with-tabbar)/mine/security-settings/pay-password/page.tsx
"use client";

import * as React from "react";
import {useRequireLogin} from "@/hooks/useRequireLogin";
import {PageHeader} from "@/components/page-header";
import {useForm} from "react-hook-form";
import {zodResolver} from "@hookform/resolvers/zod";
import {z} from "zod";
import {updatePayPassword} from "@/api/customer";
import {toast} from "sonner";
import {useRouter} from "next/navigation";
import {useTranslations} from "use-intl";
import {SAFE_QUESTION_OPTIONS} from "@/constants/constants";
import TextSkeleton from "@/components/text-skeleton";
import {useEffect, useState} from "react";
import {getBlockByIdentifier} from "@/api/common";
import {Eye, EyeOff} from "lucide-react";

export default function PayPasswordPage() {
  // 页面需要登陆Hook
  useRequireLogin();

  const router = useRouter();
  const _t = useTranslations();

  const [loading, setLoading] = useState<boolean>(true);
  const [tipContent, setTipContent] = useState<string | null>(null);
  const [show, setShow] = useState(false);

  // 表单验证
  const schema = z.object({
    safe_ask: z.string().min(1, _t("mine.toolcase.question-options.default")),
    answer: z.string().min(1, _t("common.form.placeholder.enter") + _t("mine.toolcase.form-label.answer"))
      .max(50, _t("mine.security-settings.group-account.password.answer-max")),
    password: z.string().min(8, _t("mine.security-settings.group-account.pay-password.password-min")),
    confirm_password: z.string(),
  }).refine(
    (data) => data.password === data.confirm_password,
    {
      path: ["confirm_password"],
      message: _t("mine.security-settings.group-account.password.confirm-password-eq"),
    }
  );
  type FormValues = z.infer<typeof schema>;
  const {
    register,
    handleSubmit,
    formState: {errors, isSubmitting},
  } = useForm<FormValues>({
    resolver: zodResolver(schema),
    mode: "onSubmit",
  });

  // 提交表单
  const onSubmit = handleSubmit(async (values) => {
    const result = await updatePayPassword({
      safe_ask: values.safe_ask,
      answer: values.answer,
      password: values.password,
      confirm_password: values.confirm_password,
    });
    const {code, message} = result;
    if (code !== 200) {
      toast.error(message);
    } else {
      toast.success(message);

      // 跳转登录页
      router.back();
    }
  });

  useEffect(() => {
    const fetchContent = async () => {
      setLoading(true);
      const {data} = await getBlockByIdentifier('customer_pay_password_tips');
      setTipContent(data?.content || '');
      setLoading(false);
    };

    void fetchContent();
  }, []);

  return (
    <>
      <div className="flex min-h-screen justify-center bg-[#eef3f8]">
        {/* 中间内容区域，控制最大宽度模拟手机界面 */}
        <div className="w-full max-w-xl bg-[#f5f7fb] shadow-sm">
          <PageHeader title={_t("mine.setting.edit-pay-password")}/>

          <div className="bg-gray-100 flex justify-center">
            <form onSubmit={onSubmit} className="w-full bg-gray-100 px-3 py-4">
              {/* 修改二级密码 */}
              <div className="bg-white rounded-lg mb-3 overflow-hidden">
                <div className="flex items-center text-gray-600 px-4 py-3 pb-0">
                  <span className="w-1 h-4 bg-red-600 rounded mr-2"></span>
                  {_t("mine.security-settings.group-account.pay-password.password")}
                </div>
                <div className="flex items-center px-4 py-3 border-b">
                  <label className="w-2/7 text-gray-700" htmlFor="password">{_t("mine.security-settings.group-account.pay-password.password")}</label>
                  <div className="w-5/7 relative">
                    <input id="password"
                           type={show ? "text" : 'password'}
                           {...register("password")}
                           placeholder={_t("mine.security-settings.group-account.pay-password.password-placeholder")}
                           className="text-gray-600 placeholder-gray-400 focus:outline-none h-10"
                    />
                    <button
                      type="button"
                      tabIndex={-1}
                      onClick={() => setShow(!show)}
                      className="absolute right-2 top-1/2 -translate-y-1/2 h-7 w-7 flex items-center justify-center text-muted-foreground hover:text-foreground"
                    >
                      {show ? <Eye size={18} /> : <EyeOff size={18} />}
                    </button>
                  </div>
                </div>
                {errors.password && (
                  <p className="mt-1 text-xs text-red-500">{errors.password.message}</p>
                )}
                <div className="flex items-center px-4 py-3">
                  <label className="w-2/7 text-gray-700" htmlFor="confirm_password">{_t("mine.security-settings.group-account.pay-password.confirm-password")}</label>
                  <div className="w-5/7 relative">
                    <input id="confirm_password"
                           type={show ? "text" : 'password'}
                           {...register("confirm_password")}
                           placeholder={_t("mine.security-settings.group-account.pay-password.confirm-password-placeholder")}
                           className="text-gray-600 w-5/7 placeholder-gray-400 focus:outline-none h-10"
                    />
                    <button
                      type="button"
                      tabIndex={-1}
                      onClick={() => setShow(!show)}
                      className="absolute right-2 top-1/2 -translate-y-1/2 h-7 w-7 flex items-center justify-center text-muted-foreground hover:text-foreground"
                    >
                      {show ? <Eye size={18} /> : <EyeOff size={18} />}
                    </button>
                  </div>
                </div>
                {errors.confirm_password && (
                  <p className="mt-1 text-xs text-red-500">{errors.confirm_password.message}</p>
                )}
              </div>

              {/* 安全问题 */}
              <div className="bg-white rounded-lg mb-3 overflow-hidden">
                <div className="flex items-center text-gray-600 px-4 py-3 pb-0">
                  <span className="w-1 h-4 bg-red-600 rounded mr-2"></span>
                  {_t("mine.security-settings.group-account.password.safe-ask-valid")}
                </div>
                <div className="flex items-center px-4 py-3 border-b">
                  <label className="w-2/7 text-gray-700"
                         htmlFor="safe_ask">{_t("mine.toolcase.form-label.question")}</label>
                  <select id="safe_ask" {...register("safe_ask")}
                          className="text-gray-600 w-5/7 placeholder-gray-400 focus:outline-none h-10">
                    <option value="">{_t("mine.toolcase.question-options.default")}</option>
                    {SAFE_QUESTION_OPTIONS.map(({value, i18nKey}) => (
                      <option key={`safe-option-key-${value}`} value={value}>
                        {_t(i18nKey)}
                      </option>
                    ))}
                  </select>
                </div>
                {errors.safe_ask && (
                  <p className="mt-1 text-xs text-red-500">{errors.safe_ask.message}</p>
                )}
                <div className="flex items-center px-4 py-3">
                  <label className="w-2/7 text-gray-700"
                         htmlFor="answer">{_t("mine.toolcase.form-label.answer")}</label>
                  <input type="text" id="answer"
                         {...register("answer")}
                         placeholder={_t("common.form.placeholder.enter") + _t("mine.toolcase.form-label.answer")}
                         className="text-gray-600 w-5/7 placeholder-gray-400 focus:outline-none h-10"
                  />
                </div>
                {errors.answer && (
                  <p className="mt-1 text-xs text-red-500">{errors.answer.message}</p>
                )}
              </div>

              <div className="rounded-lg mb-3 overflow-hidden">
                <div className="flex items-center text-gray-600 px-4 py-3  pb-0">
                  <span className="w-1 h-4 bg-red-600 rounded mr-2"></span>
                  {_t("mine.security-settings.group-account.password.tip")}
                </div>
                {/* 异步加载温馨提示 */}
                {loading ? (
                  <TextSkeleton lines={3}/>
                ) : (
                  <div
                    className="px-4 py-3 text-gray-600"
                    dangerouslySetInnerHTML={{__html: tipContent!}}
                  />
                )}
              </div>

              {/* 确认按钮 */}
              <button
                disabled={isSubmitting}
                className={`mt-10 h-12 w-full rounded-full bg-gradient-to-r from-[#ff6a3a] to-[#ff1020] text-white
                  font-medium tracking-wide transition transform active:scale-95
                  ${isSubmitting ? "opacity-60 cursor-not-allowed" : "cursor-pointer"}`
                }
              >
                {isSubmitting ? _t("common.form.button.submitting") : _t("common.form.button.submit")}
              </button>
            </form>
          </div>

          {/* 底部占位（给 TabBar 留空间） */}
          <div className="h-14"/>
        </div>
      </div>
    </>
  );
}

// src/views/mine/security/pay-password.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { useI18n } from 'vue-i18n'
import { Eye, EyeOff } from 'lucide-vue-next'
import { updatePayPassword } from '@/api/customer'
import { getBlockByIdentifier, httpConfigRKey } from '@/api/common'
import { toast } from '@/composables/useToast'
import { SAFE_QUESTION_OPTIONS } from '@/constants'
import SodiumEncryptor from '@/utils/sodium'
import PageHeader from '@/components/PageHeader.vue'

const router = useRouter()
const { t } = useI18n()

const loading = ref(true)
const tipContent = ref('')
const showPassword = ref(false)
const isSubmitting = ref(false)
const publicKey = ref('')

const formData = ref({
  safe_ask: '',
  answer: '',
  password: '',
  confirm_password: ''
})
const errors = ref<Record<string, string>>({})

// 验证表单
const validate = () => {
  errors.value = {}

  if (!formData.value.safe_ask) {
    errors.value.safe_ask = t('mine.toolcase.question-options.default')
    return false
  }

  if (!formData.value.answer) {
    errors.value.answer = t('common.form.placeholder.enter') + t('mine.toolcase.form-label.answer')
    return false
  }

  if (formData.value.answer.length > 50) {
    errors.value.answer = t('mine.security-settings.group-account.password.answer-max')
    return false
  }

  if (!formData.value.password || formData.value.password.length < 8) {
    errors.value.password = t('mine.security-settings.group-account.pay-password.password-min')
    return false
  }

  if (formData.value.password !== formData.value.confirm_password) {
    errors.value.confirm_password = t('mine.security-settings.group-account.password.confirm-password-eq')
    return false
  }

  return true
}

// 提交表单
const handleSubmit = async () => {
  if (!validate()) return

  isSubmitting.value = true
  try {
    // 加密密码
    const encryptedPassword = await SodiumEncryptor.encrypt(formData.value.password, publicKey.value)
    const encryptedConfirmPassword = await SodiumEncryptor.encrypt(formData.value.confirm_password, publicKey.value)

    const res = await updatePayPassword({
      safe_ask: formData.value.safe_ask,
      answer: formData.value.answer,
      password: encryptedPassword,
      confirm_password: encryptedConfirmPassword
    })

    if (res.code === 200) {
      toast.success(res.message || '修改成功')
      router.back()
    } else {
      toast.error(res.message || '修改失败')
    }
  } catch (error) {
    toast.error('修改失败')
  } finally {
    isSubmitting.value = false
  }
}

// 加载提示内容
onMounted(async () => {
  try {
    const res = await getBlockByIdentifier('customer_pay_password_tips')
    tipContent.value = res.data?.content || ''
  } catch (error) {
    console.error('加载提示内容失败', error)
  } finally {
    loading.value = false
  }

  // 获取公钥
  httpConfigRKey().then(({ data, code }) => {
    if (code === 200) publicKey.value = data.key
  })
})
</script>

<template>
  <div class="flex min-h-screen justify-center bg-[#eef3f8]">
    <div class="w-full max-w-xl bg-[#f5f7fb] shadow-sm">
      <PageHeader :title="t('mine.setting.edit-pay-password')" />

      <div class="bg-gray-100 flex justify-center">
        <form @submit.prevent="handleSubmit" class="w-full bg-gray-100 px-3 py-4">
          <!-- 修改二级密码 -->
          <div class="bg-white rounded-lg mb-3 overflow-hidden">
            <div class="flex items-center text-gray-600 px-4 py-3 pb-0">
              <span class="w-1 h-4 bg-red-600 rounded mr-2"></span>
              {{ t('mine.security-settings.group-account.pay-password.password') }}
            </div>
            <div class="flex items-center px-4 py-3 border-b">
              <label class="w-2/7 text-gray-700">{{ t('mine.security-settings.group-account.pay-password.password') }}</label>
              <div class="w-5/7 relative">
                <input
                  v-model="formData.password"
                  :type="showPassword ? 'text' : 'password'"
                  :placeholder="t('mine.security-settings.group-account.pay-password.password-placeholder')"
                  class="text-gray-600 placeholder-gray-400 focus:outline-none h-10 w-full pr-10"
                />
                <button
                  type="button"
                  @click="showPassword = !showPassword"
                  class="absolute right-2 top-1/2 -translate-y-1/2 h-7 w-7 flex items-center justify-center text-gray-400 hover:text-gray-600"
                >
                  <Eye v-if="showPassword" :size="18" />
                  <EyeOff v-else :size="18" />
                </button>
              </div>
            </div>
            <p v-if="errors.password" class="mt-1 px-4 text-xs text-red-500">{{ errors.password }}</p>

            <div class="flex items-center px-4 py-3">
              <label class="w-2/7 text-gray-700">{{ t('mine.security-settings.group-account.pay-password.confirm-password') }}</label>
              <div class="w-5/7 relative">
                <input
                  v-model="formData.confirm_password"
                  :type="showPassword ? 'text' : 'password'"
                  :placeholder="t('mine.security-settings.group-account.pay-password.confirm-password-placeholder')"
                  class="text-gray-600 placeholder-gray-400 focus:outline-none h-10 w-full pr-10"
                />
                <button
                  type="button"
                  @click="showPassword = !showPassword"
                  class="absolute right-2 top-1/2 -translate-y-1/2 h-7 w-7 flex items-center justify-center text-gray-400 hover:text-gray-600"
                >
                  <Eye v-if="showPassword" :size="18" />
                  <EyeOff v-else :size="18" />
                </button>
              </div>
            </div>
            <p v-if="errors.confirm_password" class="mt-1 px-4 text-xs text-red-500">{{ errors.confirm_password }}</p>
          </div>

          <!-- 安全问题 -->
          <div class="bg-white rounded-lg mb-3 overflow-hidden">
            <div class="flex items-center text-gray-600 px-4 py-3 pb-0">
              <span class="w-1 h-4 bg-red-600 rounded mr-2"></span>
              {{ t('mine.security-settings.group-account.password.safe-ask-valid') }}
            </div>
            <div class="flex items-center px-4 py-3 border-b">
              <label class="w-2/7 text-gray-700">{{ t('mine.toolcase.form-label.question') }}</label>
              <select
                v-model="formData.safe_ask"
                class="text-gray-600 w-5/7 placeholder-gray-400 focus:outline-none h-10"
              >
                <option value="">{{ t('mine.toolcase.question-options.default') }}</option>
                <option
                  v-for="option in SAFE_QUESTION_OPTIONS"
                  :key="option.value"
                  :value="option.value"
                >
                  {{ t(option.i18nKey) }}
                </option>
              </select>
            </div>
            <p v-if="errors.safe_ask" class="mt-1 px-4 text-xs text-red-500">{{ errors.safe_ask }}</p>

            <div class="flex items-center px-4 py-3">
              <label class="w-2/7 text-gray-700">{{ t('mine.toolcase.form-label.answer') }}</label>
              <input
                v-model="formData.answer"
                type="text"
                :placeholder="t('common.form.placeholder.enter') + t('mine.toolcase.form-label.answer')"
                class="text-gray-600 w-5/7 placeholder-gray-400 focus:outline-none h-10"
              />
            </div>
            <p v-if="errors.answer" class="mt-1 px-4 text-xs text-red-500">{{ errors.answer }}</p>
          </div>

          <!-- 温馨提示 -->
          <div class="rounded-lg mb-3 overflow-hidden">
            <div class="flex items-center text-gray-600 px-4 py-3 pb-0">
              <span class="w-1 h-4 bg-red-600 rounded mr-2"></span>
              {{ t('mine.security-settings.group-account.password.tip') }}
            </div>

            <template v-if="loading">
              <div class="px-4 py-3 space-y-2">
                <div v-for="i in 3" :key="i" class="h-4 bg-gray-200 rounded animate-pulse"></div>
              </div>
            </template>
            <div v-else class="px-4 py-3 text-gray-600" v-html="tipContent"></div>
          </div>

          <!-- 确认按钮 -->
          <button
            type="submit"
            :disabled="isSubmitting"
            :class="[
              'mt-10 h-12 w-full rounded-full bg-gradient-to-r from-[#ff6a3a] to-[#ff1020] text-white font-medium tracking-wide transition transform active:scale-95',
              isSubmitting ? 'opacity-60 cursor-not-allowed' : 'cursor-pointer'
            ]"
          >
            {{ isSubmitting ? t('common.form.button.submitting') : t('common.form.button.submit') }}
          </button>
        </form>
      </div>

      <div class="h-14"></div>
    </div>
  </div>
</template>
