// src/views/mine/receipt-text/deposit/index.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import { depositRecords } from '@/api/customer'
import { toast } from '@/composables/useToast'
import type { DepositRecordField } from '@/types/customer.type'

const list = ref<DepositRecordField[]>([])
const page = ref(1)
const hasMore = ref(true)
const loading = ref(false)
const loadMoreRef = ref<HTMLDivElement | null>(null)
let observer: IntersectionObserver | null = null

const fetchData = async (pageNo: number) => {
  loading.value = true
  try {
    const { code, data, message } = await depositRecords({
      pagination: {
        page: pageNo,
        size: 20
      }
    })
    await new Promise((r) => setTimeout(r, 500))
    if (code === 200) {
      if (data.length < 20) {
        hasMore.value = false
      }
      if (pageNo === 1) {
        list.value = []
      }
      list.value = [...list.value, ...data]
    } else {
      toast.error(message)
    }
  } catch (error) {
    toast.error('获取数据失败')
  } finally {
    loading.value = false
  }
}

onMounted(async () => {
  await fetchData(1)

  if (loadMoreRef.value && hasMore.value) {
    observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting && !loading.value) {
          const nextPage = page.value + 1
          page.value = nextPage
          fetchData(nextPage)
        }
      },
      { threshold: 1 }
    )
    observer.observe(loadMoreRef.value)
  }
})

onUnmounted(() => {
  if (observer) {
    observer.disconnect()
  }
})
</script>

<template>
  <div
    v-for="(item, index) in list"
    :key="`all-key-${index}`"
    class="grid grid-cols-[1.2fr_0.8fr_0.8fr_1fr] px-3 py-3 border-b text-sm items-center"
  >
    <!-- 来源 -->
    <div class="text-center">
      <div class="text-gray-900">{{ item?.type_label || '' }}</div>
    </div>

    <!-- 变化前 -->
    <div class="text-center font-medium text-red-500">{{ (item?.b_deposit || 0).toLocaleString() }}</div>

    <!-- 变化 -->
    <div class="text-center font-medium text-red-500">{{ (item?.deposit || 0).toLocaleString() }}</div>

    <!-- 余额 -->
    <div class="flex justify-center items-center gap-1 text-red-500 font-medium">
      {{ (item?.a_deposit || 0).toLocaleString() }}
      <img
        src="/ranking/coin.png"
        alt="coin"
        class="inline-block w-[13px] h-[13px]"
      />
    </div>
  </div>

  <!-- 底部哨兵 -->
  <div v-if="hasMore" ref="loadMoreRef" class="py-4 text-center text-xs text-gray-400">
    {{ loading ? '加载中...' : '上拉加载更多' }}
  </div>

  <div v-if="!hasMore" class="py-4 text-center text-xs text-gray-400">
    没有更多数据了
  </div>
</template>

// src/app/[locale]/(with-tabbar)/mine/receipt-text/deposit/page.tsx
"use client"

import Image from "next/image";
import {useEffect, useRef, useState} from "react";
import {depositRecords} from "@/api/customer";
import {toast} from "sonner";
import {DepositRecordField} from "@/types/customer.type";
import {useFormatter, useTranslations} from "use-intl";

export default function DepositPage() {
  // 格式化金额
  const format = useFormatter();
  const _t = useTranslations();
  const [list, setList] = useState<DepositRecordField[]>([]);
  const [page, setPage] = useState(1);
  const [hasMore, setHasMore] = useState(true);
  const [loading, setLoading] = useState(false);

  const loadMoreRef = useRef<HTMLDivElement | null>(null);

  const fetchData = async (pageNo: number) => {
    setLoading(true);
    // 请求接口
    const {code, data, message} = await depositRecords({
      pagination: {
        page: pageNo,
        size: 20,
      }
    })
    await new Promise((r) => setTimeout(r, 500));
    if (code === 200) {
      setLoading(false);
      if (data.length < 20) {
        setHasMore(false);
      }
      if (pageNo == 1) {
        setList([]);
      }
      setList((prev) => [...prev, ...data]);
    } else {
      toast.error(message);
    }
  };

  useEffect(() => {
    const levelOptions = async () => {
      await fetchData(1);
    }
    void levelOptions();
  }, []);

  useEffect(() => {
    if (!loadMoreRef.current || !hasMore) return;

    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting && !loading) {
          const nextPage = page + 1;
          setPage(nextPage);
          void fetchData(nextPage);
        }
      },
      {threshold: 1}
    );

    observer.observe(loadMoreRef.current);

    return () => observer.disconnect();
  }, [page, hasMore, loading]);

  return (
    <>
      {list.map((item, index) => (
        <div
          key={`all-key-${index}`}
          className="grid grid-cols-[1.2fr_0.8fr_0.8fr_1fr] px-3 py-3 border-b text-sm items-center"
        >
          {/* 来源 */}
          <div className="text-center">
            <div className="text-foreground">{item?.type_label || ''}</div>
          </div>

          {/* 金额 */}
          <div className="text-center font-medium text-red-500">{format.number(item?.b_deposit || 0)}</div>

          {/* 金额 */}
          <div className="text-center font-medium text-red-500">{format.number(item?.deposit || 0)}</div>

          {/* 余额 */}
          <div className="flex justify-center items-center gap-1 text-red-500 font-medium">
            {format.number(item?.a_deposit || 0)}
            <Image
              src="/ranking/coin.png"
              alt="coin"
              width={14}
              height={14}
              className="inline-block w-[13px] h-[13px]"
            />
          </div>
        </div>
      ))}

      {/* 底部哨兵 */}
      {hasMore && (
        <div ref={loadMoreRef} className="py-4 text-center text-xs text-gray-400">
          {loading ? _t("common.loading") : _t("common.loading-hit")}
        </div>
      )}

      {!hasMore && (
        <div className="py-4 text-center text-xs text-gray-400">
          {_t("common.loading-list-empty")}
        </div>
      )}
    </>
  )
}
