// src/views/mine/challenge/index.vue
<script setup lang="ts">
import { ChevronLeft } from 'lucide-vue-next'
import { useRouter } from 'vue-router'

const router = useRouter()

const goBack = () => {
  router.back()
}
</script>

<template>
  <div class="flex min-h-screen justify-center bg-[#eef3f8]">
    <div class="w-full max-w-xl bg-[#f5f7fb] shadow-sm">
      <!-- 头部 -->
      <header class="sticky top-0 z-40 bg-gradient-to-r from-red-600 to-red-500">
        <div class="flex h-12 items-center justify-between px-3">
          <button @click="goBack" class="flex items-center text-white">
            <ChevronLeft class="h-5 w-5" />
          </button>
          <span class="text-white font-bold">闯关星星</span>
          <div class="w-5"></div>
        </div>
      </header>

      <div class="flex min-w-0 flex-1 flex-col items-center justify-center gap-6 rounded-lg border-dashed p-6 text-center text-balance md:p-12">
        <div class="flex max-w-sm flex-col items-center gap-2 text-center">
          <div class="text-lg font-medium tracking-tight">
            功能开发中...
          </div>
          <div class="text-gray-500 text-sm">
            闯关星星即将上线，敬请期待！
          </div>
        </div>
      </div>

      <div class="h-14"></div>
    </div>
  </div>
</template>

// src/app/[locale]/(with-tabbar)/mine/challenge/page.tsx
"use client";

import * as React from "react";
import {useRequireLogin} from "@/hooks/useRequireLogin";
import {PageHeader} from "@/components/page-header";
import {cn} from "@/lib/utils";

export default function Mine() {
  // 页面需要登陆Hook
  useRequireLogin();

  return (
    <>
      <div className="flex min-h-screen justify-center bg-[#eef3f8]">
        {/* 中间内容区域，控制最大宽度模拟手机界面 */}
        <div className="w-full max-w-xl bg-[#f5f7fb] shadow-sm">
          <PageHeader title="闯关星星" />

          <div
            data-slot="empty"
            className={cn(
              "flex min-w-0 flex-1 flex-col items-center justify-center gap-6 rounded-lg border-dashed p-6 text-center text-balance md:p-12",
            )}
          >
            <div
              data-slot="empty-header"
              className={cn(
                "flex max-w-sm flex-col items-center gap-2 text-center",
              )}
            >
              <div
                data-slot="empty-title"
                className={cn("text-lg font-medium tracking-tight")}
              >
                功能开发中...
              </div>
              <div
                data-slot="empty-description"
                className={cn(
                  "text-muted-foreground [&>a:hover]:text-primary text-sm/relaxed [&>a]:underline [&>a]:underline-offset-4",
                )}
              >
                闯关星星即将上线，敬请期待！
              </div>
            </div>
          </div>

          {/* 底部占位（给 TabBar 留空间） */}
          <div className="h-14"/>
        </div>
      </div>
    </>
  );
}
