// src/views/auth/register.vue
<script setup lang="ts">
import { ref, onMounted, computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useI18n } from 'vue-i18n'
import { Eye, EyeOff } from 'lucide-vue-next'
import { useAuthStore } from '@/stores/auth'
import { registration, sendSmsToMobile } from '@/api/auth'
import { httpConfigRKey, getPasswordTip } from '@/api/common'
import { toast } from '@/composables/useToast'
import SodiumEncryptor from '@/utils/sodium'

const route = useRoute()
const router = useRouter()
const { t } = useI18n()
const authStore = useAuthStore()

// 倒计时页面刷新继续保持的存储key
const STORAGE_KEY = 'sms_countdown_end_at_register'

// 表单数据
const mobile = ref('')
const verifyCode = ref('')
const password = ref('')
const confirmPassword = ref('')
const showPassword = ref(false)
const loading = ref(false)
const smsLoading = ref(false)
const countdown = ref(0)
const publicKey = ref('')
const isDisable = ref(true)

// 密码提示
const tipContent = ref('')
const tipLoading = ref(true)

// 推荐人key (从URL读取)
const recommend = computed(() => (route.query.t as string) || '')

// 倒计时定时器
let timer: ReturnType<typeof setTimeout> | null = null

// 初始化
onMounted(async () => {
  // 从 localStorage 恢复倒计时
  const endAt = Number(localStorage.getItem(STORAGE_KEY))
  if (endAt) {
    const remain = Math.floor((endAt - Date.now()) / 1000)
    if (remain > 0) {
      countdown.value = remain
      startCountdownTimer()
    } else {
      localStorage.removeItem(STORAGE_KEY)
    }
  }

  // 获取公钥
  httpConfigRKey().then(({ data, code }) => {
    if (code === 200) publicKey.value = data.key
  })

  // 获取密码提示
  tipLoading.value = true
  try {
    const { data } = await getPasswordTip()
    tipContent.value = data?.content || ''
  } catch {
    // ignore
  } finally {
    tipLoading.value = false
  }
})

// 启动倒计时定时器
const startCountdownTimer = () => {
  if (timer) clearTimeout(timer)

  if (countdown.value <= 0) {
    localStorage.removeItem(STORAGE_KEY)
    return
  }

  timer = setTimeout(() => {
    countdown.value--
    if (countdown.value <= 0) {
      localStorage.removeItem(STORAGE_KEY)
    } else {
      startCountdownTimer()
    }
  }, 1000)
}

// 发送验证码
const handleSendSms = async () => {
  if (!mobile.value || smsLoading.value || countdown.value > 0) return

  smsLoading.value = true
  try {
    const res = await sendSmsToMobile(mobile.value)
    if (res.code === 200) {
      const duration = 60
      countdown.value = duration
      const endAt = Date.now() + duration * 1000
      localStorage.setItem(STORAGE_KEY, String(endAt))
      startCountdownTimer()
      toast.success(res.message || '发送成功')
    } else {
      toast.error(res.message || t('common.sms-verify_code-send-failed'))
    }
  } catch {
    toast.error(t('common.sms-verify_code-send-failed'))
  } finally {
    smsLoading.value = false
  }
}

// 注册
const handleRegister = async () => {
  if (!mobile.value || !verifyCode.value || !password.value || !confirmPassword.value || loading.value) return

  if (password.value !== confirmPassword.value) {
    toast.error(t('register.confirm_password-eq'))
    return
  }

  loading.value = true
  try {
    // 加密密码
    const encryptedPassword = await SodiumEncryptor.encrypt(password.value, publicKey.value)
    const encryptedConfirmPassword = await SodiumEncryptor.encrypt(confirmPassword.value, publicKey.value)

    const res = await registration({
      mobile: mobile.value,
      verify_code: verifyCode.value,
      password: encryptedPassword,
      confirm_password: encryptedConfirmPassword,
      recommend: recommend.value || ''
    })

    if (res.code === 200 && res.data?.access_token) {
      toast.success(res.message || '注册成功')
      authStore.setToken(
        res.data.access_token,
        res.data.token_type,
        res.data.expires_at
      )
      await authStore.fetchCurrentCustomer()
      router.replace('/')
    } else {
      toast.error(res.message || t('common.catch-error'))
    }
  } catch {
    toast.error(t('common.catch-error'))
  } finally {
    loading.value = false
  }
}

// 手机号输入变化
const onMobileChange = (e: Event) => {
  const target = e.target as HTMLInputElement
  mobile.value = target.value
  isDisable.value = target.value.length === 0
}
</script>

<template>
  <div class="flex min-h-screen justify-center bg-[#eef3f8]">
    <div class="w-full max-w-xl bg-[#f5f7fb] shadow-sm">
      <main class="px-3 pb-20 pt-3">
        <div class="pt-13 flex items-center justify-center">
          <img src="/login-logo.png" alt="Login" class="w-32 h-auto" />
        </div>

        <form @submit.prevent="handleRegister" class="mt-5">
          <div class="bg-white rounded-xl shadow-sm p-2">
            <!-- 手机号 -->
            <div class="flex justify-center items-center border-b border-gray-200">
              <label class="w-1/4 text-gray-700">{{ t('register.mobile-label') }}</label>
              <div class="w-3/4">
                <input
                  type="text"
                  :placeholder="t('register.mobile-placeholder')"
                  :value="mobile"
                  @input="onMobileChange"
                  class="w-3/4 text-gray-800 placeholder-gray-400 focus:outline-none h-12"
                />
              </div>
            </div>

            <!-- 验证码 -->
            <div class="flex justify-center items-center border-b border-gray-200">
              <label class="w-1/4 text-gray-700">{{ t('common.sms-verify_code-label') }}</label>
              <div class="flex w-3/4 items-center gap-2 flex-wrap sm:flex-nowrap">
                <input
                  type="text"
                  :placeholder="t('common.sms-verify_code-placeholder')"
                  v-model="verifyCode"
                  class="flex-1 min-w-0 text-gray-800 placeholder-gray-400 focus:outline-none h-12"
                />
                <button
                  type="button"
                  :disabled="countdown > 0 || smsLoading || isDisable"
                  @click="handleSendSms"
                  :class="[
                    'shrink-0 h-8 px-3 rounded text-xs whitespace-nowrap transition',
                    countdown > 0 || smsLoading || isDisable
                      ? 'bg-gray-600 text-white cursor-not-allowed'
                      : 'bg-blue-600 text-white active:scale-95 cursor-pointer'
                  ]"
                >
                  {{ smsLoading ? t('common.sms-verify_code-sending') : countdown > 0 ? `${countdown}s` : t('common.sms-verify_code-send-btn') }}
                </button>
              </div>
            </div>

            <!-- 密码 -->
            <div class="flex justify-center items-center border-b border-gray-200">
              <label class="w-1/4 text-gray-700">{{ t('register.password-label') }}</label>
              <div class="w-3/4 relative">
                <input
                  :type="showPassword ? 'text' : 'password'"
                  v-model="password"
                  :placeholder="t('register.password-placeholder')"
                  class="w-3/4 text-gray-800 placeholder-gray-400 focus:outline-none h-12"
                />
                <button
                  type="button"
                  tabindex="-1"
                  @click="showPassword = !showPassword"
                  class="absolute right-2 top-1/2 -translate-y-1/2 h-7 w-7 flex items-center justify-center text-gray-400 hover:text-gray-600"
                >
                  <Eye v-if="showPassword" :size="18" />
                  <EyeOff v-else :size="18" />
                </button>
              </div>
            </div>

            <!-- 确认密码 -->
            <div class="flex justify-center items-center">
              <label class="w-1/4 text-gray-700">{{ t('register.confirm_password-label') }}</label>
              <div class="w-3/4 relative">
                <input
                  :type="showPassword ? 'text' : 'password'"
                  v-model="confirmPassword"
                  :placeholder="t('register.confirm_password-placeholder')"
                  class="w-3/4 text-gray-800 placeholder-gray-400 focus:outline-none h-12"
                />
                <button
                  type="button"
                  tabindex="-1"
                  @click="showPassword = !showPassword"
                  class="absolute right-2 top-1/2 -translate-y-1/2 h-7 w-7 flex items-center justify-center text-gray-400 hover:text-gray-600"
                >
                  <Eye v-if="showPassword" :size="18" />
                  <EyeOff v-else :size="18" />
                </button>
              </div>
            </div>
          </div>

          <!-- 密码提示 -->
          <div class="rounded-lg mb-3 overflow-hidden">
            <div class="flex items-center text-gray-600 px-4 py-3 pb-0">
              <span class="w-1 h-4 bg-red-600 rounded mr-2"></span>
              {{ t('mine.security-settings.group-account.password.tip') }}
            </div>

            <!-- 骨架屏 -->
            <template v-if="tipLoading">
              <div class="px-4 py-3 space-y-2">
                <div v-for="i in 3" :key="i" class="h-4 bg-gray-200 rounded animate-pulse"></div>
              </div>
            </template>

            <!-- 内容 -->
            <div
              v-else
              class="px-4 py-3 text-gray-600"
              v-html="tipContent"
            ></div>
          </div>

          <button
            type="submit"
            :disabled="loading"
            :class="[
              'mt-10 h-12 w-full rounded-full bg-gradient-to-r from-[#ff6a3a] to-[#ff1020] text-white font-medium tracking-wide transition transform active:scale-95',
              loading ? 'opacity-60 cursor-not-allowed' : 'cursor-pointer'
            ]"
          >
            {{ loading ? t('common.form.button.submitting') : t('register.form-submit-button') }}
          </button>
        </form>

        <router-link
          to="/auth/login"
          class="flex justify-center items-center mt-6 text-[rgb(0,0,238)]"
        >
          {{ t('register.back-login') }}
        </router-link>
      </main>
    </div>
  </div>
</template>

// src/app/[locale]/(single-page)/auth/register/page.tsx
"use client";

import React, {useEffect, useRef, useState} from "react";
import Image from "next/image";
import {useForm} from "react-hook-form";
import {zodResolver} from "@hookform/resolvers/zod";
import {z} from "zod";
import {registration, sendSmsToMobile} from '@/api/auth';
import {toast} from "sonner";
import {useParams, useRouter, useSearchParams} from "next/navigation";
import Link from "next/link";
import {useTranslations} from "use-intl";
import {cn} from "@/lib/utils";
import TextSkeleton from "@/components/text-skeleton";
import {getPasswordTip} from "@/api/common";
import {useAuthStore} from "@/utils/storage/auth";
import {Eye, EyeOff} from "lucide-react";

// 倒计时页面刷新继续保持的存储key
const STORAGE_KEY = "sms_countdown_end_at_register";

export default function RegisterPage() {
  const _t = useTranslations();
  const searchParams = useSearchParams();
  const params = useParams();
  const locale = params.locale as string;
  // 原样保留
  const queryString = searchParams.toString();
  const [show, setShow] = useState(false);

  const schema = z.object({
    mobile: z.string().min(1, _t('register.mobile-placeholder')).regex(/^1[3-9]\d{9}$/, _t("register.mobile-regex")),
    verify_code: z.string().min(1, _t('common.sms-verify_code-placeholder')).max(6, _t('common.sms-verify_code-max')),
    password: z.string().min(8, _t("register.password-placeholder")),
    confirm_password: z.string(),
  }).refine(
    (data) => data.password === data.confirm_password,
    {
      path: ["confirm_password"],
      message: _t("register.confirm_password-eq"),
    }
  );

  type FormValues = z.infer<typeof schema>;
  const {
    register,
    handleSubmit,
    getValues,
    setError,
    clearErrors,
    formState: {errors, isSubmitting},
  } = useForm<FormValues>({
    resolver: zodResolver(schema),
    mode: "onChange",
  });
  const router = useRouter();

  const [loading, setLoading] = useState<boolean>(true);
  const [tipContent, setTipContent] = useState<string | null>(null);

  // 发送短信相关
  const duration = 60;
  const [countdown, setCountdown] = useState(0);
  const [isSending, setIsSending] = useState(false);
  const [isDisable, setIsDisable] = useState(true);
  const timerRef = useRef<NodeJS.Timeout | null>(null);
  // 初始化：从 localStorage 恢复
  useEffect(() => {
    const endAt = Number(localStorage.getItem(STORAGE_KEY));
    if (!endAt) return;

    const remain = Math.floor((endAt - Date.now()) / 1000);
    if (remain > 0) {
      setCountdown(remain);
    } else {
      localStorage.removeItem(STORAGE_KEY);
    }
  }, []);
  const sendSms = async () => {
    if (countdown > 0 || isSending) return;

    const mobile = getValues("mobile").trim();
    if (mobile.length < 1) {
      setError("mobile", {
        type: "manual",
        message: _t('register.mobile-placeholder'),
      });
      return;
    }

    // 立刻锁定， 防止重复点击
    setIsSending(true);
    try {
      const {code, message} = await sendSmsToMobile(mobile);
      if (code !== 200) {
        toast.error(message);
      } else {
        setCountdown(duration);
        const endAt = Date.now() + duration * 1000;
        localStorage.setItem(STORAGE_KEY, String(endAt));
        toast.success(message);
      }
    } catch (error) {
      const msg = error instanceof Error ? error.message : _t('common.sms-verify_code-send-failed');
      toast.error(msg);
    } finally {
      setIsSending(false);
    }
  };
  useEffect(() => {
    if (countdown <= 0) {
      return;
    }

    timerRef.current = setTimeout(() => {
      setCountdown((c) => c - 1);
      if (countdown <= 1) {
        localStorage.removeItem(STORAGE_KEY);
      }
    }, 1000);

    return () => {
      if (timerRef.current) {
        clearTimeout(timerRef.current);
      }
    };
  }, [countdown]);

  const setToken = useAuthStore((s) => s.setToken);

  // 表单提交
  const onSubmit = handleSubmit(async (values) => {
    // 推荐人的key
    const recommend = searchParams.get('t');
    const {code, message, data} = await registration({
      mobile: values.mobile,
      verify_code: values.verify_code,
      password: values.password,
      confirm_password: values.password,
      recommend: recommend || '',
    });
    if (code !== 200) {
      toast.error(message);
    } else {
      toast.success(message);

      // 设置token
      // 用 Zustand 统一设置
      setToken(data?.access_token, data?.token_type, data?.expires_at);

      router.replace(`/${locale}`);
    }
  });

  useEffect(() => {
    const fetchContent = async () => {
      setLoading(true);
      const {data} = await getPasswordTip();
      setTipContent(data?.content || '');
      setLoading(false);
    };

    void fetchContent();
  }, []);

  return (
    <div className="flex min-h-screen justify-center bg-[#eef3f8]">
      {/* 中间内容区域，控制最大宽度模拟手机界面 */}
      <div className="w-full max-w-xl bg-[#f5f7fb] shadow-sm">
        <main className="px-3 pb-20 pt-3">
          <div className="pt-13 flex items-center justify-center">
            <Image src={"/login-logo.png"} alt={'Login'} width={200} height={200} className="w-32 h-auto" priority/>
          </div>

          <form onSubmit={onSubmit} className="mt-5">
            <div className="bg-white rounded-xl shadow-sm p-2">
              {/* 手机号 */}
              <div className="flex justify-center items-center border-b border-gray-200">
                <label className="w-1/4 text-gray-700" htmlFor={'mobile'}>{_t('register.mobile-label')}</label>
                <div className="w-3/4">
                  <input
                    id="mobile"
                    type="text"
                    placeholder={_t('register.mobile-placeholder')}
                    {...register("mobile")}
                    className=" w-3/4 text-gray-800 placeholder-gray-400 focus:outline-none h-12"
                    onChange={(e)  => {
                      if  (e.target.value.length > 0) {
                        setIsDisable(false);
                        clearErrors("mobile");
                      } else {
                        setIsDisable(true);
                      }
                    }}
                  />
                </div>
              </div>
              {errors.mobile && (
                <p className="mt-1 text-xs text-red-500">{errors.mobile.message}</p>
              )}
              {/* 验证码 */}
              <div className="flex justify-center items-center border-b border-gray-200">
                <label className="w-1/4 text-gray-700" htmlFor={'verify_code'}>{_t('common.sms-verify_code-label')}</label>
                <div className="flex w-3/4 items-center gap-2 flex-wrap sm:flex-nowrap">
                  <input
                    id="verify_code"
                    type="text"
                    placeholder={_t('common.sms-verify_code-placeholder')}
                    {...register("verify_code")}
                    className="flex-1 min-w-0 text-gray-800 placeholder-gray-400 focus:outline-none h-12"
                  />
                  <button
                    type="button"
                    disabled={countdown > 0 || isSending || isDisable}
                    onClick={sendSms}
                    className={cn(
                      "shrink-0 h-8 px-3 rounded text-xs whitespace-nowrap transition",
                      countdown > 0 || isSending || isDisable
                        ? "bg-gray-600 text-white cursor-not-allowed"
                        : "bg-blue-600 text-white active:scale-95 cursor-pointer"
                    )}
                  >
                    {/*{sendButI18Key}*/}
                    {isSending ? _t('common.sms-verify_code-sending') : countdown > 0 ? `${countdown}s` : _t('common.sms-verify_code-send-btn')}
                  </button>
                </div>
              </div>
              {errors.verify_code && (
                <p className="mt-1 text-xs text-red-500">{errors.verify_code.message}</p>
              )}

              {/* 密码 */}
              <div className="flex justify-center items-center border-b border-gray-200">
                <label className="w-1/4 text-gray-700" htmlFor={'password'}>{_t('register.password-label')}</label>
                <div className="w-3/4 relative">
                  <input
                    id="password"
                    type={show ? "text" : 'password'}
                    {...register("password")}
                    placeholder={_t('register.password-placeholder')}
                    className=" w-3/4 text-gray-800 placeholder-gray-400 focus:outline-none h-12"
                  />
                  <button
                    type="button"
                    tabIndex={-1}
                    onClick={() => setShow(!show)}
                    className="absolute right-2 top-1/2 -translate-y-1/2 h-7 w-7 flex items-center justify-center text-muted-foreground hover:text-foreground"
                  >
                    {show ? <Eye size={18} /> : <EyeOff size={18} />}
                  </button>
                </div>
              </div>
              {errors.password && (
                <p className="mt-1 text-xs text-red-500">{errors.password.message}</p>
              )}

              {/* 确认密码 */}
              <div className="flex justify-center items-center">
                <label className="w-1/4 text-gray-700" htmlFor={'confirm_password'}>{_t('register.confirm_password-label')}</label>
                <div className="w-3/4 relative">
                  <input
                    id="confirm_password"
                    type={show ? "text" : 'password'}
                    {...register("confirm_password")}
                    placeholder={_t('register.confirm_password-placeholder')}
                    className=" w-3/4 text-gray-800 placeholder-gray-400 focus:outline-none h-12"
                  />
                  <button
                    type="button"
                    tabIndex={-1}
                    onClick={() => setShow(!show)}
                    className="absolute right-2 top-1/2 -translate-y-1/2 h-7 w-7 flex items-center justify-center text-muted-foreground hover:text-foreground"
                  >
                    {show ? <Eye size={18} /> : <EyeOff size={18} />}
                  </button>
                </div>
              </div>
              {errors.confirm_password && (
                <p className="mt-1 text-xs text-red-500">{errors.confirm_password.message}</p>
              )}
            </div>

            <div className="rounded-lg mb-3 overflow-hidden">
              <div className="flex items-center text-gray-600 px-4 py-3  pb-0">
                <span className="w-1 h-4 bg-red-600 rounded mr-2"></span>
                {_t("mine.security-settings.group-account.password.tip")}
              </div>

              {/* 异步加载温馨提示 */}
              {loading ? (
                <TextSkeleton lines={3}/>
              ) : (
                <div
                  className="px-4 py-3 text-gray-600"
                  dangerouslySetInnerHTML={{__html: tipContent!}}
                />
              )}
            </div>

            <button
              disabled={isSubmitting}
              className={`mt-10 h-12 w-full rounded-full bg-gradient-to-r from-[#ff6a3a] to-[#ff1020] text-white
              font-medium tracking-wide transition transform active:scale-95
              ${isSubmitting ? "opacity-60 cursor-not-allowed" : "cursor-pointer"}`
              }
            >
              {isSubmitting ? _t("common.form.button.submitting") : _t('register.form-submit-button')}
            </button>
          </form>
          <Link href={`/${locale}/auth/login?${queryString}`}
                className={"flex justify-center items-center mt-6 text-[rgb(0,0,238)]"}
          >{_t('register.back-login')}</Link>
        </main>
      </div>
    </div>
  );
}
