// src/app/[locale]/(with-tabbar)/mine/edit-nickname/page.tsx
"use client";

import * as React from "react";
import {useRequireLogin} from "@/hooks/useRequireLogin";
import {useForm} from "react-hook-form";
import {zodResolver} from "@hookform/resolvers/zod";
import {AlertCircleIcon} from "lucide-react";
import Image from "next/image";
import {z} from "zod";
import {PageHeader} from "@/components/page-header";
import {Alert, AlertTitle} from "@/components/ui/alert";
import {updateNickname} from "@/api/customer";
import {toast} from "sonner";
import {useRouter} from "next/navigation";
import {useTranslations} from "use-intl";

const schema = z.object({
  nickname: z.string().min(1, "请输入昵称").max(50),
});
type FormValues = z.infer<typeof schema>;

export default function Mine() {
  // 页面需要登陆Hook
  useRequireLogin();
  const router = useRouter();
  const _t = useTranslations();

  const {
    register,
    handleSubmit,
    formState: {errors, isSubmitting},
  } = useForm<FormValues>({
    resolver: zodResolver(schema),
    mode: "onChange",
  });

  const onSubmit = handleSubmit(async (values) => {
    const result = await updateNickname({
      nickname: values.nickname,
    });
    const {code, message} = result;
    if (code !== 200) {
      toast.error(message);
    } else {
      toast.success(message);

      router.back();
    }
  })

  return (
    <>
      <div className="flex min-h-screen justify-center bg-[#eef3f8]">
        {/* 中间内容区域，控制最大宽度模拟手机界面 */}
        <div className="w-full max-w-xl bg-[#f5f7fb] shadow-sm">
          <PageHeader title={_t("mine.setting.edit-nickname")} />
          {/* 提示 */}
          <main className="px-3 pb-20 pt-3">
            <Alert variant="destructive">
              <div className="flex items-center gap-2">
                <AlertCircleIcon />
                <AlertTitle>
                  {_t("mine.edit-nickname.alert")}
                  <Image
                    src="/ranking/coin.png"
                    alt="gold"
                    width={13}
                    height={13}
                    className="inline-block ml-1 w-[13px] h-[13px]"
                  />
                </AlertTitle>
              </div>
            </Alert>

            {/* 提交表单 */}
            <form onSubmit={onSubmit} className="mt-5">
              <div className="bg-white rounded-xl shadow-sm p-2">
                <div className="flex justify-center items-center ">
                  <label className="w-2/7 text-gray-700">{_t("mine.profile.form-label.nickname")}</label>
                  <input
                    type="text"
                    placeholder={_t("common.form.placeholder.enter") + _t("mine.profile.form-label.nickname")}
                    {...register("nickname")}
                    className="w-5/7 text-gray-800 placeholder-gray-400 focus:outline-none h-12"
                  />
                </div>
                {errors.nickname && (
                  <p className="mt-1 text-xs text-red-500">{errors.nickname.message}</p>
                )}
              </div>

              <button
                disabled={isSubmitting}
                className={`mt-10 h-12 w-full rounded-full bg-gradient-to-r from-[#ff6a3a] to-[#ff1020] text-white
                  font-medium tracking-wide transition transform active:scale-95
                  ${isSubmitting ? "opacity-60 cursor-not-allowed" : "cursor-pointer"}`
                }
              >
                {isSubmitting ? _t("common.form.button.submitting") : _t("common.form.button.submit")}
              </button>
            </form>
          </main>

          {/* 底部占位（给 TabBar 留空间） */}
          <div className="h-14"/>
        </div>
      </div>
    </>
  );
}

// src/views/mine/profile/edit-nickname.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useI18n } from 'vue-i18n'
import { AlertCircle } from 'lucide-vue-next'
import { updateNickname } from '@/api/customer'
import { toast } from '@/composables/useToast'
import PageHeader from '@/components/PageHeader.vue'

const router = useRouter()
const { t } = useI18n()

const nickname = ref('')
const error = ref('')
const isSubmitting = ref(false)

// 验证
const validate = () => {
  error.value = ''
  if (!nickname.value.trim()) {
    error.value = '请输入昵称'
    return false
  }
  if (nickname.value.length > 50) {
    error.value = '昵称最多50个字符'
    return false
  }
  return true
}

// 提交
const handleSubmit = async () => {
  if (!validate()) return

  isSubmitting.value = true
  try {
    const res = await updateNickname({ nickname: nickname.value })
    if (res.code === 200) {
      toast.success(res.message || '修改成功')
      router.back()
    } else {
      toast.error(res.message || '修改失败')
    }
  } catch (e) {
    toast.error('修改失败')
  } finally {
    isSubmitting.value = false
  }
}
</script>

<template>
  <div class="min-h-screen bg-[#f5f7fb] pb-16">
    <PageHeader :title="t('mine.setting.edit-nickname')" />

    <main class="px-3 pb-20 pt-3">
      <!-- 警告提示 -->
      <div class="p-3 bg-red-50 border border-red-200 rounded-lg flex items-center gap-2">
        <AlertCircle class="w-5 h-5 text-red-500 flex-shrink-0" />
        <span class="text-red-600 text-sm">
          {{ t('mine.edit-nickname.alert') }}
          <img src="/ranking/coin.png" alt="coin" class="inline-block ml-1 w-[13px] h-[13px]" />
        </span>
      </div>

      <!-- 表单 -->
      <form @submit.prevent="handleSubmit" class="mt-5">
        <div class="bg-white rounded-xl shadow-sm p-3">
          <div class="flex items-center gap-2">
            <label class="text-gray-700 w-16 flex-shrink-0">{{ t('mine.profile.form-label.nickname') }}</label>
            <input
              v-model="nickname"
              type="text"
              :placeholder="t('common.form.placeholder.enter') + t('mine.profile.form-label.nickname')"
              class="flex-1 text-gray-800 placeholder-gray-400 focus:outline-none h-12"
            />
          </div>
          <p v-if="error" class="mt-1 text-xs text-red-500">{{ error }}</p>
        </div>

        <button
          type="submit"
          :disabled="isSubmitting"
          :class="[
            'mt-10 h-12 w-full rounded-full bg-gradient-to-r from-[#ff6a3a] to-[#ff1020] text-white font-medium tracking-wide transition transform active:scale-95',
            isSubmitting ? 'opacity-60 cursor-not-allowed' : 'cursor-pointer'
          ]"
        >
          {{ isSubmitting ? t('common.form.button.submitting') : t('common.form.button.submit') }}
        </button>
      </form>
    </main>
  </div>
</template>
