// src/app/[locale]/(with-tabbar)/mine/profile/page.tsx
"use client";

import * as React from "react";
import {PageHeader} from "@/components/page-header";
import {useParams, useRouter} from "next/navigation";
import {useForm} from "react-hook-form";
import {zodResolver} from "@hookform/resolvers/zod";
import {toast} from "sonner";
import {z} from "zod";
import {getMemberField, updateProfile} from "@/api/customer";
import {AlertCircleIcon, ChevronRight} from "lucide-react";
import {Alert, AlertTitle} from "@/components/ui/alert";
import Link from "next/link";
import {useEffect} from "react";
import {MemberField} from "@/types/customer.type";
import {useRequireLogin} from "@/hooks/useRequireLogin";
import {useTranslations} from "use-intl";

/**
 * 我的资料
 * @constructor
 */
export default function ProfilePage() {
  // 页面需要登陆Hook
  useRequireLogin();
  const router = useRouter();
  const params = useParams();
  const locale = params.locale as string;
  const _t = useTranslations();

  const [profile, setProfile] = React.useState<MemberField>();

  const schema = z.object({
    realname: z.string().trim().refine(
      (v) => v === "" || v.length <= 50,
      {message: _t("mine.profile.validation.realname")}
    ),
    qq: z.string().trim().refine(
      (v) => v === "" || /^\d{5,12}$/.test(v),
      {message: _t("mine.profile.validation.qq")}
    ),
    alipay: z.string().trim().refine(
      (v) => v === "" || v.length <= 50,
      {message: _t("mine.profile.validation.alipay")}
    ),
    wchat: z.string().trim().refine(
      (v) => v === "" || v.length <= 50,
      {message: _t("mine.profile.validation.wchat")}
    ),
    address: z.string().trim().refine(
      (v) => v === "" || v.length <= 150,
      {message: _t("mine.profile.validation.address")}
    ),
    signature: z.string().trim().refine(
      (v) => v === "" || v.length <= 200,
      {message: _t("mine.profile.validation.signature")}
    ),
  });
  type FormValues = z.infer<typeof schema>;

  const {
    register,
    setValue,
    handleSubmit,
    formState: {errors, isSubmitting},
  } = useForm<FormValues>({
    resolver: zodResolver(schema),
    mode: "onSubmit",
  });

  useEffect(() => {
    const fetchProfile = async () => {
      const {code, data} = await getMemberField();
      if (code === 200) {
        setProfile(data)
        if (data?.signature) {
          setValue("signature", data.signature)
        }
      }
    };

    void fetchProfile();
  }, [setValue]);

  /**
   * 提交数据
   */
  const onSubmit = handleSubmit(async (values) => {
    const hasAnyValue = Object.values(values).some(
      (v) => {
        return v && v.trim() !== ""
      }
    );
    if (!hasAnyValue) {
      toast.warning("你未填写任何数据，无需提交");
      return;
    }
    const result = await updateProfile({
      qq: values.qq,
      wchat: values.wchat,
      alipay: values.alipay,
      realname: values.realname,
      address: values.address,
      signature: values.signature,
    });
    const {code, message} = result;
    if (code !== 200) {
      toast.error(message);
    } else {
      toast.success(message);

      router.back();
    }
  })

  return (
    <>
      <div className="flex min-h-screen justify-center bg-[#eef3f8]">
        {/* 中间内容区域，控制最大宽度模拟手机界面 */}
        <div className="w-full max-w-xl bg-[#f5f7fb] shadow-sm">
          <PageHeader title={_t("mine.setting.profile")} />

          {/* 提示 */}
          <main className="px-3 pb-20 pt-3">
            <div className="bg-white rounded-xl shadow-sm p-2 mt-2">
              <div className="flex justify-center items-center ">
                <div className="flex w-3/5">
                  <div className="w-4/9 text-gray-500">{_t("mine.profile.form-label.nickname")}</div>
                  <div className="w-6/7 text-gray-700">{profile?.nickname}</div>
                </div>
                <Link className="flex justify-end w-2/5 cursor-pointer text-red-700" href={`/${locale}/mine/edit-nickname`}>
                  {_t("mine.profile.edit-nickname")}<ChevronRight/>
                </Link>
              </div>
            </div>
            <div className="bg-white rounded-xl shadow-sm p-2 mt-2">
              <div className="flex justify-center items-center">
                {profile?.email ?
                  <>
                    <div className="w-1/5 text-gray-500">{_t("mine.profile.form-label.email")}</div>
                    <div className="flex items-center ml-1 w-4/5 text-[#c8c9cc] placeholder-gray-400 focus:outline-none">{profile?.email}</div>
                  </>
                  :
                  <>
                    <div className="w-3/5 text-gray-500">{_t("mine.profile.form-label.email")}</div>
                    <Link className="flex justify-end ml-1 w-2/5 text-red-700" href={`/${locale}/mine/bind-email`}>
                      {_t("mine.bind-email.title")}<ChevronRight/>
                    </Link>
                  </>
                }
              </div>
            </div>
            <div className="bg-white rounded-xl shadow-sm p-2 mt-2">
              <div className="flex justify-center items-center">
                <div className="w-1/5 text-gray-500">{_t("mine.profile.form-label.mobile")}</div>
                <div className="flex ml-1 w-4/5 text-[#c8c9cc]">{profile?.mobile}</div>
              </div>
            </div>

            {/* 提交表单 */}
            <form onSubmit={onSubmit} className="mt-5">
              <div className="bg-white rounded-xl shadow-sm p-2 mt-2">
                <div className="flex justify-center items-center ">
                  <label className="w-1/5 text-gray-500">{_t("mine.profile.form-label.qq")}</label>
                  {profile?.qq ?
                    <div className="flex items-center ml-1 w-4/5 text-[#c8c9cc] placeholder-gray-400 focus:outline-none h-10">{profile?.qq}</div>
                    :
                    <input
                      type="text"
                      placeholder={_t("common.form.placeholder.enter") + _t("mine.profile.form-label.qq")}
                      {...register("qq")}
                      disabled={!!profile?.qq}
                      className="ml-1 w-4/5 text-gray-800 placeholder-gray-400 focus:outline-none h-10"
                    />
                  }
                </div>
                {errors.qq && (
                  <p className="mt-1 text-xs text-red-500">{errors.qq.message}</p>
                )}
              </div>
              <div className="bg-white rounded-xl shadow-sm p-2 mt-2">
                <div className="flex justify-center items-center ">
                  <label className="w-1/5 text-gray-500">{_t("mine.profile.form-label.alipay")}</label>
                  {profile?.alipay ?
                    <div className="flex items-center ml-1 w-4/5 text-[#c8c9cc] placeholder-gray-400 focus:outline-none h-10">{profile?.alipay}</div>
                    :
                    <input
                      type="text"
                      placeholder={_t("common.form.placeholder.enter") + _t("mine.profile.form-label.alipay")}
                      {...register("alipay")}
                      disabled={!!profile?.alipay}
                      className="ml-1 w-4/5 text-gray-800 placeholder-gray-400 focus:outline-none h-10"
                    />
                  }
                </div>
                {errors.alipay && (
                  <p className="mt-1 text-xs text-red-500">{errors.alipay.message}</p>
                )}
              </div>
              <div className="bg-white rounded-xl shadow-sm p-2 mt-2">
                <div className="flex justify-center items-center ">
                  <label className="w-1/5 text-gray-500">{_t("mine.profile.form-label.wchat")}</label>
                  {profile?.wchat ?
                    <div className="flex items-center ml-1 w-4/5 text-[#c8c9cc] placeholder-gray-400 focus:outline-none h-10">{profile?.wchat}</div>
                    :
                    <input
                      type="text"
                      placeholder={_t("common.form.placeholder.enter") + _t("mine.profile.form-label.wchat")}
                      {...register("wchat")}
                      disabled={!!profile?.wchat}
                      className="ml-1 w-4/5 text-gray-800 placeholder-gray-400 focus:outline-none h-10"
                    />
                  }
                </div>
                {errors.wchat && (
                  <p className="mt-1 text-xs text-red-500">{errors.wchat.message}</p>
                )}
              </div>
              <div className="bg-white rounded-xl shadow-sm p-2 mt-2">
                <div className="flex justify-center items-center ">
                  <label className="w-1/5 text-gray-500">{_t("mine.profile.form-label.realname")}</label>
                  {profile?.realname ?
                    <div className="flex items-center ml-1 w-4/5 text-[#c8c9cc] placeholder-gray-400 focus:outline-none h-10">{profile?.realname}</div>
                    : <input
                      type="text"
                      placeholder={_t("common.form.placeholder.enter") + _t("mine.profile.form-label.realname")}
                      {...register("realname")}
                      disabled={!!profile?.realname}
                      className="ml-1 w-4/5 text-gray-800 placeholder-gray-400 focus:outline-none h-10"
                    />
                  }
                </div>
                {errors.realname && (
                  <p className="mt-1 text-xs text-red-500">{errors.realname.message}</p>
                )}
              </div>
              <div className="bg-white rounded-xl shadow-sm p-2 mt-2">
                <div className="flex justify-center items-center ">
                  <label className="w-1/5 text-gray-500">{_t("mine.profile.form-label.address")}</label>
                  {profile?.address ?
                    <div className="flex items-center ml-1 w-4/5 text-[#c8c9cc] placeholder-gray-400 focus:outline-none h-10">{profile?.address}</div>
                    :
                    <input
                      type="text"
                      placeholder={_t("common.form.placeholder.enter") + _t("mine.profile.form-label.address")}
                      {...register("address")}
                      disabled={!!profile?.address}
                      className="ml-1 w-4/5 text-gray-800 placeholder-gray-400 focus:outline-none h-10"
                    />
                  }
                </div>
                {errors.address && (
                  <p className="mt-1 text-xs text-red-500">{errors.address.message}</p>
                )}
              </div>
              <Alert variant="destructive" className="mt-2 ">
                <div className="flex items-center gap-2">
                  <AlertCircleIcon/>
                  <AlertTitle>{_t("mine.profile.alert")}</AlertTitle>
                </div>
              </Alert>
              <div className="bg-white rounded-xl shadow-sm p-2 mt-2">
                <div className="flex justify-center items-center ">
                  <label className="w-1/5 text-gray-500">{_t("mine.profile.form-label.signature")}</label>
                  <textarea
                    placeholder={_t("common.form.placeholder.enter") + _t("mine.profile.form-label.signature")}
                    {...register("signature")}
                    className="ml-1 w-4/5 text-gray-800 placeholder-gray-400 focus:outline-none h-20"
                  />
                </div>
                {errors.signature && (
                  <p className="mt-1 text-xs text-red-500">{errors.signature.message}</p>
                )}
              </div>

              <button
                disabled={isSubmitting && !!profile?.aid}
                className={`mt-10 h-12 w-full rounded-full bg-gradient-to-r from-[#ff6a3a] to-[#ff1020] text-white
                  font-medium tracking-wide transition transform active:scale-95
                  ${isSubmitting ? "opacity-60 cursor-not-allowed" : "cursor-pointer"}`
                }
              >
                {isSubmitting ? _t("common.form.button.submitting") : _t("common.form.button.submit")}
              </button>
            </form>
          </main>

          {/* 底部占位（给 TabBar 留空间） */}
          <div className="h-14"/>
        </div>
      </div>
    </>
  );
}

// src/views/mine/profile/index.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { useI18n } from 'vue-i18n'
import { ChevronRight, AlertCircle } from 'lucide-vue-next'
import { getMemberField, updateProfile } from '@/api/customer'
import { toast } from '@/composables/useToast'
import type { MemberField } from '@/types/customer.type'
import PageHeader from '@/components/PageHeader.vue'

const router = useRouter()
const { t } = useI18n()

const profile = ref<MemberField | null>(null)
const isLoading = ref(true)
const isSubmitting = ref(false)

// 表单数据
const formData = ref({
  qq: '',
  alipay: '',
  wchat: '',
  realname: '',
  address: '',
  signature: ''
})

// 表单错误
const errors = ref<Record<string, string>>({})

// 加载用户资料
const loadProfile = async () => {
  try {
    isLoading.value = true
    const res = await getMemberField()
    if (res.code === 200 && res.data) {
      profile.value = res.data
      // 设置签名
      if (res.data.signature) {
        formData.value.signature = res.data.signature
      }
    }
  } catch (error) {
    console.error('加载资料失败:', error)
  } finally {
    isLoading.value = false
  }
}

// 验证表单
const validateForm = () => {
  errors.value = {}

  if (formData.value.qq && !/^\d{5,12}$/.test(formData.value.qq)) {
    errors.value.qq = t('mine.profile.validation.qq')
  }

  if (formData.value.realname && formData.value.realname.length > 50) {
    errors.value.realname = t('mine.profile.validation.realname')
  }

  if (formData.value.alipay && formData.value.alipay.length > 50) {
    errors.value.alipay = t('mine.profile.validation.alipay')
  }

  if (formData.value.wchat && formData.value.wchat.length > 50) {
    errors.value.wchat = t('mine.profile.validation.wchat')
  }

  if (formData.value.address && formData.value.address.length > 150) {
    errors.value.address = t('mine.profile.validation.address')
  }

  if (formData.value.signature && formData.value.signature.length > 200) {
    errors.value.signature = t('mine.profile.validation.signature')
  }

  return Object.keys(errors.value).length === 0
}

// 提交表单
const handleSubmit = async () => {
  if (!validateForm()) return

  // 检查是否有任何数据
  const hasAnyValue = Object.values(formData.value).some(v => v && v.trim() !== '')
  if (!hasAnyValue) {
    toast.warning('你未填写任何数据，无需提交')
    return
  }

  try {
    isSubmitting.value = true
    const res = await updateProfile({
      qq: formData.value.qq || undefined,
      wchat: formData.value.wchat || undefined,
      alipay: formData.value.alipay || undefined,
      realname: formData.value.realname || undefined,
      address: formData.value.address || undefined,
      signature: formData.value.signature || undefined
    })

    if (res.code === 200) {
      toast.success(res.message || '保存成功')
      router.back()
    } else {
      toast.error(res.message || '保存失败')
    }
  } catch (error) {
    toast.error('保存失败')
  } finally {
    isSubmitting.value = false
  }
}

onMounted(() => {
  loadProfile()
})
</script>

<template>
  <div class="min-h-screen bg-[#f5f7fb] pb-16">
    <PageHeader :title="t('mine.setting.profile')" />

    <main class="px-3 pb-20 pt-3">
      <!-- 昵称 -->
      <div class="bg-white rounded-xl shadow-sm p-3 mt-2">
        <div class="flex justify-between items-center">
          <div class="flex items-center gap-2">
            <span class="text-gray-500 w-16">{{ t('mine.profile.form-label.nickname') }}</span>
            <span class="text-gray-700">{{ profile?.nickname || '-' }}</span>
          </div>
          <router-link to="/mine/edit-nickname" class="flex items-center text-red-600 text-sm">
            {{ t('mine.profile.edit-nickname') }}
            <ChevronRight class="w-4 h-4" />
          </router-link>
        </div>
      </div>

      <!-- 邮箱 -->
      <div class="bg-white rounded-xl shadow-sm p-3 mt-2">
        <div class="flex justify-between items-center">
          <div class="flex items-center gap-2">
            <span class="text-gray-500 w-16">{{ t('mine.profile.form-label.email') }}</span>
            <span v-if="profile?.email" class="text-gray-400">{{ profile.email }}</span>
          </div>
          <router-link v-if="!profile?.email" to="/mine/bind-email" class="flex items-center text-red-600 text-sm">
            {{ t('mine.bind-email.title') }}
            <ChevronRight class="w-4 h-4" />
          </router-link>
        </div>
      </div>

      <!-- 手机 -->
      <div class="bg-white rounded-xl shadow-sm p-3 mt-2">
        <div class="flex items-center gap-2">
          <span class="text-gray-500 w-16">{{ t('mine.profile.form-label.mobile') }}</span>
          <span class="text-gray-400">{{ profile?.mobile || '-' }}</span>
        </div>
      </div>

      <!-- 表单 -->
      <form @submit.prevent="handleSubmit" class="mt-5">
        <!-- QQ -->
        <div class="bg-white rounded-xl shadow-sm p-3 mt-2">
          <div class="flex items-center gap-2">
            <label class="text-gray-500 w-16 flex-shrink-0">{{ t('mine.profile.form-label.qq') }}</label>
            <template v-if="profile?.qq">
              <span class="text-gray-400">{{ profile.qq }}</span>
            </template>
            <template v-else>
              <input
                v-model="formData.qq"
                type="text"
                :placeholder="t('common.form.placeholder.enter') + t('mine.profile.form-label.qq')"
                class="flex-1 text-gray-800 placeholder-gray-400 focus:outline-none h-10"
              />
            </template>
          </div>
          <p v-if="errors.qq" class="mt-1 text-xs text-red-500">{{ errors.qq }}</p>
        </div>

        <!-- 支付宝 -->
        <div class="bg-white rounded-xl shadow-sm p-3 mt-2">
          <div class="flex items-center gap-2">
            <label class="text-gray-500 w-16 flex-shrink-0">{{ t('mine.profile.form-label.alipay') }}</label>
            <template v-if="profile?.alipay">
              <span class="text-gray-400">{{ profile.alipay }}</span>
            </template>
            <template v-else>
              <input
                v-model="formData.alipay"
                type="text"
                :placeholder="t('common.form.placeholder.enter') + t('mine.profile.form-label.alipay')"
                class="flex-1 text-gray-800 placeholder-gray-400 focus:outline-none h-10"
              />
            </template>
          </div>
          <p v-if="errors.alipay" class="mt-1 text-xs text-red-500">{{ errors.alipay }}</p>
        </div>

        <!-- 微信 -->
        <div class="bg-white rounded-xl shadow-sm p-3 mt-2">
          <div class="flex items-center gap-2">
            <label class="text-gray-500 w-16 flex-shrink-0">{{ t('mine.profile.form-label.wchat') }}</label>
            <template v-if="profile?.wchat">
              <span class="text-gray-400">{{ profile.wchat }}</span>
            </template>
            <template v-else>
              <input
                v-model="formData.wchat"
                type="text"
                :placeholder="t('common.form.placeholder.enter') + t('mine.profile.form-label.wchat')"
                class="flex-1 text-gray-800 placeholder-gray-400 focus:outline-none h-10"
              />
            </template>
          </div>
          <p v-if="errors.wchat" class="mt-1 text-xs text-red-500">{{ errors.wchat }}</p>
        </div>

        <!-- 真实姓名 -->
        <div class="bg-white rounded-xl shadow-sm p-3 mt-2">
          <div class="flex items-center gap-2">
            <label class="text-gray-500 w-16 flex-shrink-0">{{ t('mine.profile.form-label.realname') }}</label>
            <template v-if="profile?.realname">
              <span class="text-gray-400">{{ profile.realname }}</span>
            </template>
            <template v-else>
              <input
                v-model="formData.realname"
                type="text"
                :placeholder="t('common.form.placeholder.enter') + t('mine.profile.form-label.realname')"
                class="flex-1 text-gray-800 placeholder-gray-400 focus:outline-none h-10"
              />
            </template>
          </div>
          <p v-if="errors.realname" class="mt-1 text-xs text-red-500">{{ errors.realname }}</p>
        </div>

        <!-- 地址 -->
        <div class="bg-white rounded-xl shadow-sm p-3 mt-2">
          <div class="flex items-center gap-2">
            <label class="text-gray-500 w-16 flex-shrink-0">{{ t('mine.profile.form-label.address') }}</label>
            <template v-if="profile?.address">
              <span class="text-gray-400">{{ profile.address }}</span>
            </template>
            <template v-else>
              <input
                v-model="formData.address"
                type="text"
                :placeholder="t('common.form.placeholder.enter') + t('mine.profile.form-label.address')"
                class="flex-1 text-gray-800 placeholder-gray-400 focus:outline-none h-10"
              />
            </template>
          </div>
          <p v-if="errors.address" class="mt-1 text-xs text-red-500">{{ errors.address }}</p>
        </div>

        <!-- 警告提示 -->
        <div class="mt-2 p-3 bg-red-50 border border-red-200 rounded-lg flex items-center gap-2">
          <AlertCircle class="w-5 h-5 text-red-500 flex-shrink-0" />
          <span class="text-red-600 text-sm">{{ t('mine.profile.alert') }}</span>
        </div>

        <!-- 个性签名 -->
        <div class="bg-white rounded-xl shadow-sm p-3 mt-2">
          <div class="flex items-start gap-2">
            <label class="text-gray-500 w-16 flex-shrink-0 pt-2">{{ t('mine.profile.form-label.signature') }}</label>
            <textarea
              v-model="formData.signature"
              :placeholder="t('common.form.placeholder.enter') + t('mine.profile.form-label.signature')"
              class="flex-1 text-gray-800 placeholder-gray-400 focus:outline-none h-20 resize-none"
            />
          </div>
          <p v-if="errors.signature" class="mt-1 text-xs text-red-500">{{ errors.signature }}</p>
        </div>

        <!-- 提交按钮 -->
        <button
          type="submit"
          :disabled="isSubmitting"
          :class="[
            'mt-10 h-12 w-full rounded-full bg-gradient-to-r from-[#ff6a3a] to-[#ff1020] text-white font-medium tracking-wide transition transform active:scale-95',
            isSubmitting ? 'opacity-60 cursor-not-allowed' : 'cursor-pointer'
          ]"
        >
          {{ isSubmitting ? t('common.form.button.submitting') : t('common.form.button.submit') }}
        </button>
      </form>
    </main>
  </div>
</template>
