// src/app/[locale]/(with-tabbar)/mine/salary/record/page.tsx
"use client"

import Image from "next/image";
import {useEffect, useRef, useState} from "react";
import * as React from "react";
import {useTranslations} from "use-intl";
import {salaryRecords} from "@/api/customer";
import {toast} from "sonner";
import {SalaryRecordField} from "@/types/customer.type";
import dayjs from "@/lib/dayjs";

export default function AllPage() {
  const _t = useTranslations();

  const [list, setList] = useState<SalaryRecordField[]>([]);
  const [page, setPage] = useState(1);
  const [hasMore, setHasMore] = useState(true);
  const [loading, setLoading] = useState(false);

  const loadMoreRef = useRef<HTMLDivElement | null>(null);

  const fetchData = async (pageNo: number) => {
    setLoading(true);

    // 请求接口
    const {code, data, message} = await salaryRecords({
      pagination: {
        page: pageNo,
        size: 20,
      }
    })
    await new Promise((r) => setTimeout(r, 555));
    if (code === 200) {
      setLoading(false);
      if (data.length < 20) {
        setHasMore(false);
      }
      if (pageNo == 1) {
        setList([]);
      }
      setList((prev) => [...prev, ...data]);
    } else {
      toast.error(message);
    }
  };

  useEffect(() => {
    const initList = async () => {
      await fetchData(1);
    }
    void initList();
  }, []);

  useEffect(() => {
    if (!loadMoreRef.current || !hasMore) return;

    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting && !loading) {
          const nextPage = page + 1;
          setPage(nextPage);
          void fetchData(nextPage);
        }
      },
      {threshold: 1}
    );

    observer.observe(loadMoreRef.current);

    return () => observer.disconnect();
  }, [page, hasMore, loading]);

  return (
    <>
      {/* 表头 */}
      <div className="grid grid-cols-[0.2fr_0.8fr_0.5fr_1fr] px-3 py-2 text-xs text-muted-foreground border-b bg-white">
        <div>{_t('mine.salary.record-grid-1')}</div>
        <div className="text-center">{_t('mine.salary.record-grid-2')}</div>
        <div className="text-center">{_t('mine.salary.record-grid-3')}</div>
        <div className="text-right">{_t('mine.salary.record-grid-4')}</div>
      </div>

      {list.map((item, index) => (
        <div
          key={`all-key-${index}`}
          className="grid grid-cols-[0.2fr_0.8fr_0.5fr_1fr] px-3 py-3 border-b text-sm items-center"
        >
          {/* 类型 */}
          <div className="leading-tight">{item.typestr}</div>

          {/* 统计金额 */}
          <div className="text-center font-medium">{item.basecoin}</div>

          {/* 获得工资 */}
          <div className="text-center font-medium text-red-500">
            {item.coin}
            <Image
              src="/ranking/coin.png"
              alt="coin"
              width={13}
              height={13}
              className="inline-block w-[13px] h-[13px]"
            />
          </div>

          {/* 记录日期 */}
          <div className="flex justify-end items-center gap-1 font-medium">
            {dayjs.unix(item?.addtime || 0).format("YYYY-MM-DD")}
          </div>
        </div>
      ))}

      {/* 底部哨兵 */}
      {hasMore && (
        <div ref={loadMoreRef} className="py-4 text-center text-xs text-gray-400">
          {loading ? _t("common.loading") : _t("common.loading-hit")}
        </div>
      )}

      {!hasMore && (
        <div className="py-4 text-center text-xs text-gray-400">
          {_t("common.loading-list-empty")}
        </div>
      )}
    </>
  )
}

// src/views/mine/salary/record/index.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import { salaryRecords } from '@/api/customer'
import { toast } from '@/composables/useToast'
import type { SalaryRecordField } from '@/types/customer.type'
import dayjs from 'dayjs'

const list = ref<SalaryRecordField[]>([])
const page = ref(1)
const hasMore = ref(true)
const loading = ref(false)
const loadMoreRef = ref<HTMLDivElement | null>(null)
let observer: IntersectionObserver | null = null

const fetchData = async (pageNo: number) => {
  loading.value = true
  try {
    const { code, data, message } = await salaryRecords({
      pagination: {
        page: pageNo,
        size: 20
      }
    })
    await new Promise((r) => setTimeout(r, 555))
    if (code === 200) {
      if (data.length < 20) {
        hasMore.value = false
      }
      if (pageNo === 1) {
        list.value = []
      }
      list.value = [...list.value, ...data]
    } else {
      toast.error(message)
    }
  } catch (error) {
    toast.error('获取数据失败')
  } finally {
    loading.value = false
  }
}

onMounted(async () => {
  await fetchData(1)

  if (loadMoreRef.value && hasMore.value) {
    observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting && !loading.value) {
          const nextPage = page.value + 1
          page.value = nextPage
          fetchData(nextPage)
        }
      },
      { threshold: 1 }
    )
    observer.observe(loadMoreRef.value)
  }
})

onUnmounted(() => {
  if (observer) {
    observer.disconnect()
  }
})
</script>

<template>
  <!-- 表头 -->
  <div class="grid grid-cols-[0.2fr_0.8fr_0.5fr_1fr] px-3 py-2 text-xs text-gray-500 border-b bg-white">
    <div>类型</div>
    <div class="text-center">统计金额</div>
    <div class="text-center">获得工资</div>
    <div class="text-right">记录日期</div>
  </div>

  <div
    v-for="(item, index) in list"
    :key="`all-key-${index}`"
    class="grid grid-cols-[0.2fr_0.8fr_0.5fr_1fr] px-3 py-3 border-b text-sm items-center"
  >
    <!-- 类型 -->
    <div class="leading-tight">{{ item.typestr }}</div>

    <!-- 统计金额 -->
    <div class="text-center font-medium">{{ item.basecoin }}</div>

    <!-- 获得工资 -->
    <div class="text-center font-medium text-red-500">
      {{ item.coin }}
      <img
        src="/ranking/coin.png"
        alt="coin"
        class="inline-block w-[13px] h-[13px]"
      />
    </div>

    <!-- 记录日期 -->
    <div class="flex justify-end items-center gap-1 font-medium">
      {{ dayjs.unix(item?.addtime || 0).format('YYYY-MM-DD') }}
    </div>
  </div>

  <!-- 底部哨兵 -->
  <div v-if="hasMore" ref="loadMoreRef" class="py-4 text-center text-xs text-gray-400">
    {{ loading ? '加载中...' : '上拉加载更多' }}
  </div>

  <div v-if="!hasMore" class="py-4 text-center text-xs text-gray-400">
    没有更多数据了
  </div>
</template>
