// src/views/mine/receipt-text/index.vue
<script setup lang="ts">
import { computed } from 'vue'
import { ChevronLeft } from 'lucide-vue-next'
import { useRoute, useRouter } from 'vue-router'
import { useI18n } from 'vue-i18n'
import PointsPage from './points/index.vue'
import DepositPage from './deposit/index.vue'

const { t } = useI18n()
const route = useRoute()
const router = useRouter()

const currentTab = computed(() => (route.query.tab as string) || 'points')

const tabs = computed(() => [
  { key: 'points', label: t('mine.receipt-text.tab-points') },
  { key: 'deposit', label: t('mine.receipt-text.tab-deposit') }
])

const switchTab = (key: string) => {
  router.replace({ query: { ...route.query, tab: key } })
}

const goBack = () => {
  router.back()
}
</script>

<template>
  <div class="flex min-h-screen justify-center bg-[#eef3f8]">
    <div class="w-full max-w-xl bg-[#f5f7fb] shadow-sm">
      <!-- 头部 -->
      <header class="sticky top-0 z-40 bg-gradient-to-r from-red-600 to-red-500">
        <div class="flex h-12 items-center justify-between px-3">
          <button @click="goBack" class="flex items-center text-white">
            <ChevronLeft class="h-5 w-5" />
          </button>
          <span class="text-white font-bold">{{ t('mine.setting.receipt-text') }}</span>
          <div class="w-5"></div>
        </div>
      </header>

      <main>
        <div class="grid grid-cols-2 text-center text-sm bg-white">
          <button
            v-for="item in tabs"
            :key="item.key"
            @click="switchTab(item.key)"
            :class="[
              'py-3 text-center',
              currentTab === item.key
                ? 'text-red-500 font-bold border-b-2 border-red-500'
                : 'text-gray-500'
            ]"
          >
            {{ item.label }}
          </button>
        </div>

        <!-- 子页面渲染区域 -->
        <div class="p-2">
          <!-- 积分记录表头 -->
          <div v-if="currentTab === 'points'" class="grid grid-cols-[1.2fr_0.8fr_0.8fr_0.8fr_1fr] px-3 py-2 text-xs text-gray-500 border-b">
            <div class="text-center">{{ t('mine.receipt-text.header-time') }}</div>
            <div class="text-center">{{ t('mine.receipt-text.header-before') }}</div>
            <div class="text-center">{{ t('mine.receipt-text.header-change') }}</div>
            <div class="text-center">{{ t('mine.receipt-text.header-after') }}</div>
            <div class="text-center">{{ t('mine.receipt-text.header-type') }}</div>
          </div>

          <!-- 账户记录表头 -->
          <div v-else-if="currentTab === 'deposit'" class="grid grid-cols-[1.2fr_0.8fr_0.8fr_0.8fr_1fr] px-3 py-2 text-xs text-gray-500 border-b">
            <div class="text-center">{{ t('mine.receipt-text.header-time') }}</div>
            <div class="text-center">{{ t('mine.receipt-text.header-before') }}</div>
            <div class="text-center">{{ t('mine.receipt-text.header-change') }}</div>
            <div class="text-center">{{ t('mine.receipt-text.header-after') }}</div>
            <div class="text-center">{{ t('mine.receipt-text.header-type') }}</div>
          </div>

          <PointsPage v-if="currentTab === 'points'" />
          <DepositPage v-else-if="currentTab === 'deposit'" />
        </div>
      </main>

      <div class="h-14"></div>
    </div>
  </div>
</template>

// src/app/[locale]/(with-tabbar)/mine/receipt-text/page.tsx
"use client";

import * as React from "react";
import {useRequireLogin} from "@/hooks/useRequireLogin";
import {PageHeader} from "@/components/page-header";
import Link from "next/link";
import {redirect, useParams, useSearchParams} from "next/navigation";

import PointsPage from "./points/page";
import DepositPage from "./deposit/page";
import {useTranslations} from "use-intl";

export default function ReceiptTextPage() {
  // 页面需要登陆Hook
  useRequireLogin();

  const _t = useTranslations();
  const params = useParams();
  const searchParams = useSearchParams();
  const locale = params.locale as string;

  const current = searchParams.get("tab");
  const fromDrawer = searchParams.get("from") === "drawer";

  // 默认跳转到 /today
  if (!current) {
    const params = new URLSearchParams(searchParams.toString());
    params.set("tab", "points");
    redirect(`/${locale}/mine/receipt-text?${params.toString()}`);
  }

  // ------------- Tabs 定义 ----------------
  const tabs = [
    {key: "points", i18Key: "capital-record.tab-1"},
    {key: "deposit", i18Key: "capital-record.tab-2"}
  ];

  return (
    <>
      <div className="flex min-h-screen justify-center bg-[#eef3f8]">
        {/* 中间内容区域，控制最大宽度模拟手机界面 */}
        <div className="w-full max-w-xl bg-[#f5f7fb] shadow-sm">
          <PageHeader title={_t("mine.setting.receipt-text")}
                      cBack={fromDrawer ? `/${locale}/mine?drawer=setting` : undefined}/>

          <main className="">
            <div className="grid grid-cols-2 text-center text-sm bg-white">
              {tabs.map((item) => {
                const active = item.key === current;
                return (
                  <Link
                    key={item.key}
                    href={`/${locale}/mine/receipt-text?tab=${item.key}`}
                    className={`py-3 text-center ${
                      active ? "text-red-500 font-bold border-b-2 border-red-500" : "text-gray-500"
                    }`}
                  >
                    {_t(item.i18Key)}
                  </Link>
                )
              })}
            </div>

            {/* 子页面渲染区域 */}
            <div className="p-2">
              {/* 表头 */}
              <div className="grid grid-cols-[1.2fr_0.8fr_0.8fr_1fr] px-3 py-2 text-xs text-muted-foreground border-b">
                <div className="text-center">{_t('capital-record.table-header-1')}</div>
                <div className="text-center">{_t('capital-record.table-header-2')}</div>
                <div className="text-center">{_t('capital-record.table-header-3')}</div>
                <div className="text-center">{_t('capital-record.table-header-4')}</div>
              </div>
              {/* 注意：这里根据 tab 动态加载子页面模块 */}
              {current === "points" && <PointsPage/>}
              {current === "deposit" && <DepositPage/>}
            </div>
          </main>

          {/* 底部占位（给 TabBar 留空间） */}
          <div className="h-14"/>
        </div>
      </div>
    </>
  );
}
