// src/app/[locale]/(with-tabbar)/index/activities/page.tsx
"use client";

import * as React from "react";
import { useState, useEffect } from "react";
import { getActivities } from "@/api/home";
import { IndexDataItem } from "@/types/index.type";
import Link from "next/link";
import {useLocale, useTranslations} from "use-intl";
import {PageHeader} from "@/components/page-header";


export default function AnnouncementListPage() {
  const [activities, setAactivities] = useState<IndexDataItem[]>([]);
  const _t = useTranslations();

  const locale = useLocale();

  useEffect(() => {
    getActivities().then(({ code, data }) => {
      if (code === 200 && data) setAactivities(data);
    });
  }, []);

  return (
    <div className="flex min-h-screen justify-center bg-[#eef3f8]">
      <div className="w-full max-w-xl bg-[#f5f7fb] shadow-sm">

        {/* 顶部标题 */}
        <PageHeader title={_t("近期活动")}/>

        <main className="px-3 pb-20 pt-3">

          {/* 公告列表 */}
          <section className="space-y-3 px-0">
            {activities.map((item) => (
              <Link
                href={`/${locale}/index/activities/${item.id}`}
                key={item.id}
                className="block w-full bg-white rounded-lg shadow-sm overflow-hidden"
              >
                {item.pic && (
                  <img
                    src={item.pic}
                    className="w-full"
                    alt={item.title}
                  />
                )}
              </Link>
            ))}
          </section>

        </main>
      </div>
    </div>
  );
}

// src/views/home/activities/index.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useI18n } from 'vue-i18n'
import { getActivities } from '@/api/home'
import { useLocalized } from '@/composables/useLocalized'
import type { IndexDataItem } from '@/types/index.type'
import PageHeader from '@/components/PageHeader.vue'
import PageLoading from '@/components/PageLoading.vue'
import PageEmpty from '@/components/PageEmpty.vue'

const { t } = useI18n()
const { localize } = useLocalized()

const loading = ref(true)
const activities = ref<IndexDataItem[]>([])

const loadData = async () => {
  try {
    loading.value = true
    const res = await getActivities()
    if (res.code === 200) {
      activities.value = res.data || []
    }
  } catch (error) {
    console.error('加载活动失败:', error)
  } finally {
    loading.value = false
  }
}

onMounted(() => {
  loadData()
})
</script>

<template>
  <div class="min-h-screen bg-gray-50">
    <PageHeader :title="t('home.events')" />

    <PageLoading v-if="loading" />

    <template v-else>
      <PageEmpty v-if="activities.length === 0" />

      <div v-else class="space-y-3 p-4">
        <router-link
          v-for="item in activities"
          :key="item.id"
          :to="`/index/activities/${item.id}`"
          class="block rounded-lg bg-white p-4 shadow-sm"
        >
          <h3 class="font-medium text-gray-800">{{ localize(item.lang_title as Record<string, string> | null, item.title) }}</h3>
          <p class="mt-1 text-sm text-gray-500">{{ item.created_at }}</p>
        </router-link>
      </div>
    </template>
  </div>
</template>
