// src/app/[locale]/(single-page)/agent/recharge/record/page.tsx
"use client"

import {useEffect, useRef, useState} from "react";
import * as React from "react";
import {useFormatter, useLocale, useTranslations} from "use-intl";
import {toast} from "sonner";
import dayjs from "@/lib/dayjs";
import {PageHeader} from "@/components/page-header";
import {agentLogRecord} from "@/api/agent";
import {AgentLogField} from "@/types/agent.type";
import {LOCALE_CURRENCY_MAP} from "@/i18n/routing";

export default function AgentRechargeRecordPage() {
  const _t = useTranslations();
  const locale = useLocale();
  // 格式化金额
  const format = useFormatter();
  // 币种符号
  const currency = LOCALE_CURRENCY_MAP[locale] ?? 'USD';
  const loadMoreRef = useRef<HTMLDivElement | null>(null);

  const [list, setList] = useState<AgentLogField[]>([]);
  const [page, setPage] = useState(1);
  const [hasMore, setHasMore] = useState(true);
  const [loading, setLoading] = useState(false);

  const fetchData = async (pageNo: number) => {
    setLoading(true);

    // 请求接口
    const {code, data, message} = await agentLogRecord({
      search: {type: 3},
      pagination: {
        page: pageNo,
        size: 20,
      }
    })
    await new Promise((r) => setTimeout(r, 553));
    if (code === 200) {
      setLoading(false);
      if (data.length < 20) {
        setHasMore(false);
      }
      if (pageNo == 1) {
        setList([]);
      }
      setList((prev) => [...prev, ...data]);
    } else {
      toast.error(message);
    }
  };

  useEffect(() => {
    const initList = async () => {
      await fetchData(1);
    }
    void initList();
  }, []);

  useEffect(() => {
    if (!loadMoreRef.current || !hasMore) return;

    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting && !loading) {
          const nextPage = page + 1;
          setPage(nextPage);
          void fetchData(nextPage);
        }
      },
      {threshold: 1}
    );

    observer.observe(loadMoreRef.current);

    return () => observer.disconnect();
  }, [page, hasMore, loading]);

  return (
    <>
      <div className="flex min-h-screen justify-center bg-[#eef3f8]">
        {/* 中间内容区域，控制最大宽度模拟手机界面 */}
        <div className="w-full max-w-xl bg-[#f5f7fb] shadow-sm">
          <PageHeader title={_t('agent.recharge.record-title')}/>

          {/* 表头 */}
          <div className="grid grid-cols-[0.4fr_0.5fr_1fr] px-1 py-1 text-xs text-muted-foreground border-b bg-white">
            <div className="text-center">{_t('agent.recharge.record-grid-1')}</div>
            <div className="text-center">{_t('agent.recharge.record-grid-2')}</div>
            <div className="text-center">{_t('agent.recharge.record-grid-3')}</div>
          </div>

          {list.map((item, index) => (
            <div
              key={`all-key-${index}`}
              className="grid grid-cols-[0.4fr_0.5fr_1fr] px-1 py-1 border-b text-sm items-center"
            >
              {/* 记录日期 */}
              <div className="text-center font-medium">
                {dayjs.unix(item?.addtime || 0).format("YYYY-MM-DD")}
              </div>

              {/* 统计金额 */}
              <div className="text-center font-medium">
                <div className="text-red-600">{item.points}</div>
                <div>
                  {format.number(
                    (item?.points || 0) / 1000,
                    {style: 'currency', currency: currency, minimumFractionDigits: 0}
                  )}
                </div>
              </div>

              {/* 获得工资 */}
              <div className="text-center font-medium">
                {item.content}
              </div>
            </div>
          ))}

          {/* 底部哨兵 */}
          {hasMore && (
            <div ref={loadMoreRef} className="py-4 text-center text-xs text-gray-400">
              {loading ? _t("common.loading") : _t("common.loading-hit")}
            </div>
          )}

          {!hasMore && (
            <div className="py-4 text-center text-xs text-gray-400">
              {_t("common.loading-list-empty")}
            </div>
          )}

          {/* 底部占位（给 TabBar 留空间） */}
          <div className="h-14"/>
        </div>
      </div>
    </>
  )
}

// src/views/agent/recycle/record/index.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import { ChevronLeft } from 'lucide-vue-next'
import { useRouter } from 'vue-router'
import { agentLogRecord } from '@/api/agent'
import { toast } from '@/composables/useToast'
import type { AgentLogField } from '@/types/agent.type'
import dayjs from 'dayjs'

const router = useRouter()
const list = ref<AgentLogField[]>([])
const page = ref(1)
const hasMore = ref(true)
const loading = ref(false)
const loadMoreRef = ref<HTMLDivElement | null>(null)
let observer: IntersectionObserver | null = null

const fetchData = async (pageNo: number) => {
  loading.value = true
  try {
    const { code, data, message } = await agentLogRecord({
      search: { type: 4 },
      pagination: {
        page: pageNo,
        size: 20
      }
    })
    await new Promise((r) => setTimeout(r, 553))
    if (code === 200) {
      if (data.length < 20) {
        hasMore.value = false
      }
      if (pageNo === 1) {
        list.value = []
      }
      list.value = [...list.value, ...data]
    } else {
      toast.error(message)
    }
  } catch (error) {
    toast.error('获取数据失败')
  } finally {
    loading.value = false
  }
}

onMounted(async () => {
  await fetchData(1)

  if (loadMoreRef.value && hasMore.value) {
    observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting && !loading.value) {
          const nextPage = page.value + 1
          page.value = nextPage
          fetchData(nextPage)
        }
      },
      { threshold: 1 }
    )
    observer.observe(loadMoreRef.value)
  }
})

onUnmounted(() => {
  if (observer) {
    observer.disconnect()
  }
})

const goBack = () => {
  router.back()
}
</script>

<template>
  <div class="flex min-h-screen justify-center bg-[#eef3f8]">
    <div class="w-full max-w-xl bg-[#f5f7fb] shadow-sm">
      <header class="sticky top-0 z-40 bg-gradient-to-r from-red-600 to-red-500">
        <div class="flex h-12 items-center justify-between px-3">
          <button @click="goBack" class="flex items-center text-white">
            <ChevronLeft class="h-5 w-5" />
          </button>
          <span class="text-white font-bold">回收记录</span>
          <div class="w-5"></div>
        </div>
      </header>

      <!-- 表头 -->
      <div class="grid grid-cols-[0.4fr_0.5fr_1fr] px-1 py-1 text-xs text-gray-500 border-b bg-white">
        <div class="text-center">日期</div>
        <div class="text-center">积分</div>
        <div class="text-center">备注</div>
      </div>

      <div
        v-for="(item, index) in list"
        :key="`all-key-${index}`"
        class="grid grid-cols-[0.4fr_0.5fr_1fr] px-1 py-1 border-b text-sm items-center bg-white"
      >
        <!-- 记录日期 -->
        <div class="text-center font-medium">
          {{ dayjs.unix(item?.addtime || 0).format('YYYY-MM-DD') }}
        </div>

        <!-- 积分 -->
        <div class="text-center font-medium">
          <div class="text-red-600">{{ item.points }}</div>
          <div>{{ ((item?.points || 0) / 1000).toFixed(0) }}元</div>
        </div>

        <!-- 备注 -->
        <div class="text-center font-medium">
          {{ item.content }}
        </div>
      </div>

      <!-- 底部哨兵 -->
      <div v-if="hasMore" ref="loadMoreRef" class="py-4 text-center text-xs text-gray-400">
        {{ loading ? '加载中...' : '上拉加载更多' }}
      </div>

      <div v-if="!hasMore" class="py-4 text-center text-xs text-gray-400">
        没有更多数据了
      </div>

      <div class="h-14"></div>
    </div>
  </div>
</template>
