// src/views/mine/hand-coins/index.vue
<script setup lang="ts">
import { ChevronLeft } from 'lucide-vue-next'
import { useRouter } from 'vue-router'

const router = useRouter()

const goBack = () => {
  router.back()
}
</script>

<template>
  <div class="flex min-h-screen justify-center bg-[#eef3f8]">
    <div class="w-full max-w-xl bg-[#f5f7fb] shadow-sm">
      <!-- 头部 -->
      <header class="sticky top-0 z-40 bg-gradient-to-r from-red-600 to-red-500">
        <div class="flex h-12 items-center justify-between px-3">
          <button @click="goBack" class="flex items-center text-white">
            <ChevronLeft class="h-5 w-5" />
          </button>
          <span class="text-white font-bold">免费兑换</span>
          <div class="w-5"></div>
        </div>
      </header>

      <div class="bg-gray-100">
        <div class="bg-white rounded-lg mb-3 overflow-hidden px-3 py-4 mx-3 mt-3">
          <div class="flex items-center justify-between py-3 border-b">
            <span class="text-sm text-gray-700">近7日流水</span>
            <span class="flex items-center gap-1 text-sm text-red-500 font-medium">
              2,961,600
              <img
                src="/ranking/coin.png"
                alt="coin"
                class="inline-block w-[13px] h-[13px]"
              />
            </span>
          </div>
          <div class="flex items-center justify-between py-3 border-b">
            <span class="text-sm text-gray-700">近7日免手续费奖励</span>
            <span class="flex items-center gap-1 text-sm text-red-500 font-medium">
              250,000
              <img
                src="/ranking/coin.png"
                alt="coin"
                class="inline-block w-[13px] h-[13px]"
              />
            </span>
          </div>
          <div class="flex items-center justify-between py-3">
            <span class="text-sm text-gray-700">
              当前可免手续费的兑换额度
            </span>
            <span class="flex items-center gap-1 text-sm text-red-500 font-medium">
              490,400
              <img
                src="/ranking/coin.png"
                alt="coin"
                class="inline-block w-[13px] h-[13px]"
              />
            </span>
          </div>
        </div>
      </div>

      <div class="h-14"></div>
    </div>
  </div>
</template>

// src/app/[locale]/(with-tabbar)/mine/hand-coins/page.tsx
"use client";

import * as React from "react";
import {useRequireLogin} from "@/hooks/useRequireLogin";
import {PageHeader} from "@/components/page-header";
import Image from "next/image";

export default function HandCoinsPage() {
  // 页面需要登陆Hook
  useRequireLogin();

  return (
    <>
      <div className="flex min-h-screen justify-center bg-[#eef3f8]">
        {/* 中间内容区域，控制最大宽度模拟手机界面 */}
        <div className="w-full max-w-xl bg-[#f5f7fb] shadow-sm">
          <PageHeader title="免费兑换"/>

          <div className="bg-gray-100">
            <div className="bg-white rounded-lg mb-3 overflow-hidden px-3 py-4">
              <div className="flex items-center justify-between py-3 border-b">
                <span className="text-sm text-gray-700">近7日流水</span>
                <span className="flex items-center gap-1 text-sm text-red-500 font-medium">
                  2,961,600
                  <Image
                    src="/ranking/coin.png"
                    alt="coin"
                    width={14}
                    height={14}
                    className="inline-block w-[13px] h-[13px]"
                  />
                </span>
              </div>
              <div className="flex items-center justify-between py-3 border-b">
                <span className="text-sm text-gray-700">近7日免手续费奖励</span>
                <span className="flex items-center gap-1 text-sm text-red-500 font-medium">
                  250,000
                  <Image
                    src="/ranking/coin.png"
                    alt="coin"
                    width={14}
                    height={14}
                    className="inline-block w-[13px] h-[13px]"
                  />
                </span>
              </div>
              <div className="flex items-center justify-between py-3">
                <span className="text-sm text-gray-700">
                  当前可免手续费的兑换额度
                </span>
                <span className="flex items-center gap-1 text-sm text-red-500 font-medium">
                  490,400
                  <Image
                    src="/ranking/coin.png"
                    alt="coin"
                    width={14}
                    height={14}
                    className="inline-block w-[13px] h-[13px]"
                  />
                </span>
              </div>
            </div>
          </div>

          {/* 底部占位（给 TabBar 留空间） */}
          <div className="h-14"/>
        </div>
      </div>
    </>
  );
}
